#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4DA79EDA231C852B (foundation@krita.org)
#
Name     : krita
Version  : 4.4.8
Release  : 48
URL      : https://download.kde.org/stable/krita/4.4.8/krita-4.4.8.tar.gz
Source0  : https://download.kde.org/stable/krita/4.4.8/krita-4.4.8.tar.gz
Source1  : https://download.kde.org/stable/krita/4.4.8/krita-4.4.8.tar.gz.sig
Summary  : Open source painting program
Group    : Development/Tools
License  : BSD-3-Clause CC-BY-SA-4.0 GPL-2.0 GPL-3.0 LGPL-2.1 Unlicense Zlib
Requires: krita-bin = %{version}-%{release}
Requires: krita-data = %{version}-%{release}
Requires: krita-lib = %{version}-%{release}
Requires: krita-license = %{version}-%{release}
Requires: krita-locales = %{version}-%{release}
BuildRequires : PyQt5
BuildRequires : Vc-dev
BuildRequires : Vc-staticdev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-kde
BuildRequires : buildreq-qmake
BuildRequires : cmake(Vc)
BuildRequires : eigen-data
BuildRequires : eigen-dev
BuildRequires : exiv2-dev
BuildRequires : extra-cmake-modules pkgconfig(OpenEXR)
BuildRequires : extra-cmake-modules pkgconfig(poppler)
BuildRequires : extra-cmake-modules-data
BuildRequires : git
BuildRequires : gsl-dev
BuildRequires : kcrash-dev
BuildRequires : ki18n-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : openjpeg
BuildRequires : pkg-config
BuildRequires : pkgconfig(OpenColorIO)
BuildRequires : pkgconfig(exiv2)
BuildRequires : pkgconfig(fftw3)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(libopenjp2)
BuildRequires : pkgconfig(libraw)
BuildRequires : pkgconfig(libraw_r)
BuildRequires : poppler-dev
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtdeclarative-dev
BuildRequires : qtmultimedia-dev
BuildRequires : quazip-dev
BuildRequires : sip-dev
BuildRequires : tiff-dev
BuildRequires : zlib-dev
Patch1: 0001-Support-building-with-OpenEXR-3.patch

%description
Krita is a professional FREE and open source painting program. It is made by
artists that want to see affordable art tools for everyone.

%package bin
Summary: bin components for the krita package.
Group: Binaries
Requires: krita-data = %{version}-%{release}
Requires: krita-license = %{version}-%{release}

%description bin
bin components for the krita package.


%package data
Summary: data components for the krita package.
Group: Data

%description data
data components for the krita package.


%package dev
Summary: dev components for the krita package.
Group: Development
Requires: krita-lib = %{version}-%{release}
Requires: krita-bin = %{version}-%{release}
Requires: krita-data = %{version}-%{release}
Provides: krita-devel = %{version}-%{release}
Requires: krita = %{version}-%{release}

%description dev
dev components for the krita package.


%package lib
Summary: lib components for the krita package.
Group: Libraries
Requires: krita-data = %{version}-%{release}
Requires: krita-license = %{version}-%{release}

%description lib
lib components for the krita package.


%package license
Summary: license components for the krita package.
Group: Default

%description license
license components for the krita package.


%package locales
Summary: locales components for the krita package.
Group: Default

%description locales
locales components for the krita package.


%prep
%setup -q -n krita-4.4.8
cd %{_builddir}/krita-4.4.8
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1631081355
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1631081355
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/krita
cp %{_builddir}/krita-4.4.8/COPYING %{buildroot}/usr/share/package-licenses/krita/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/krita-4.4.8/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/krita/095d1f504f6fd8add73a4e4964e37f260f332b6a
cp %{_builddir}/krita-4.4.8/cmake/modules/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/krita/4577cbeb3556a519433c8f3b7476c74b55f7ef7a
cp %{_builddir}/krita-4.4.8/krita/data/aboutdata/LICENSE %{buildroot}/usr/share/package-licenses/krita/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/krita-4.4.8/krita/data/patterns/dith_license.txt %{buildroot}/usr/share/package-licenses/krita/92ebac73a2c8c52b8a305df0311eb17a025a84c2
cp %{_builddir}/krita-4.4.8/krita/integration/3rdparty/LICENSE %{buildroot}/usr/share/package-licenses/krita/b274cc52fd06db856281db3593167f8765c148c9
cp %{_builddir}/krita-4.4.8/packaging/windows/installer/license_gpl-3.0.rtf %{buildroot}/usr/share/package-licenses/krita/b6f3908b5e9bfb4f93ffbd7a442bf38a75ccb44a
cp %{_builddir}/krita-4.4.8/plugins/generators/simplexnoise/3rdparty/c-open-simplex/LICENSE %{buildroot}/usr/share/package-licenses/krita/fad0fbaf831fead007f4465821459c58a2973eb0
cp %{_builddir}/krita-4.4.8/plugins/impex/raw/3rdparty/libkdcraw/COPYING %{buildroot}/usr/share/package-licenses/krita/133efad5329acf364135c569ac01ec084c3d4647
cp %{_builddir}/krita-4.4.8/plugins/impex/raw/3rdparty/libkdcraw/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/krita/ff3ed70db4739b3c6747c7f624fe2bad70802987
cp %{_builddir}/krita-4.4.8/plugins/impex/raw/3rdparty/libkdcraw/COPYING.LIB %{buildroot}/usr/share/package-licenses/krita/9a1929f4700d2407c70b507b3b2aaf6226a9543c
pushd clr-build
%make_install
popd
%find_lang krita

%files
%defattr(-,root,root,-)
/usr/lib64/krita-python-libs/krita/__init__.py
/usr/lib64/krita-python-libs/krita/api.py
/usr/lib64/krita-python-libs/krita/attic/mikro.py
/usr/lib64/krita-python-libs/krita/attic/scripter_hooks.py
/usr/lib64/krita-python-libs/krita/decorators.py
/usr/lib64/krita-python-libs/krita/dockwidgetfactory.py
/usr/lib64/krita-python-libs/krita/excepthook.py
/usr/lib64/krita-python-libs/krita/excepthook_ui.py
/usr/lib64/krita-python-libs/krita/sceditor/__init__.py
/usr/lib64/krita-python-libs/krita/sceditor/assist.py
/usr/lib64/krita-python-libs/krita/sceditor/console.py
/usr/lib64/krita-python-libs/krita/sceditor/dockwidget.py
/usr/lib64/krita-python-libs/krita/sceditor/dockwidget_icons.py
/usr/lib64/krita-python-libs/krita/sceditor/highlighter.py
/usr/lib64/krita-python-libs/krita/sceditor/indenter.py
/usr/lib64/krita-python-libs/krita/sceditor/mainwindow.py
/usr/lib64/krita-python-libs/krita/sceditor/mainwindow_ui.py
/usr/lib64/krita-python-libs/krita/sceditor/widget.py

%files bin
%defattr(-,root,root,-)
/usr/bin/krita
/usr/bin/krita_version
/usr/bin/kritarunner

%files data
%defattr(-,root,root,-)
/usr/share/applications/krita_brush.desktop
/usr/share/applications/krita_csv.desktop
/usr/share/applications/krita_exr.desktop
/usr/share/applications/krita_heightmap.desktop
/usr/share/applications/krita_jp2.desktop
/usr/share/applications/krita_jpeg.desktop
/usr/share/applications/krita_kra.desktop
/usr/share/applications/krita_ora.desktop
/usr/share/applications/krita_pdf.desktop
/usr/share/applications/krita_png.desktop
/usr/share/applications/krita_psd.desktop
/usr/share/applications/krita_qimageio.desktop
/usr/share/applications/krita_raw.desktop
/usr/share/applications/krita_spriter.desktop
/usr/share/applications/krita_svg.desktop
/usr/share/applications/krita_tga.desktop
/usr/share/applications/krita_tiff.desktop
/usr/share/applications/krita_xcf.desktop
/usr/share/applications/org.kde.krita.desktop
/usr/share/color-schemes/KritaBlender.colors
/usr/share/color-schemes/KritaBright.colors
/usr/share/color-schemes/KritaDark.colors
/usr/share/color-schemes/KritaDarker.colors
/usr/share/color-schemes/KritaNeutral.colors
/usr/share/color/icc/krita/ACEScg-elle-V4-g10.icc
/usr/share/color/icc/krita/ClayRGB-elle-V2-g22.icc
/usr/share/color/icc/krita/ClayRGB-elle-V4-srgbtrc.icc
/usr/share/color/icc/krita/Gray-D50-elle-V2-g10.icc
/usr/share/color/icc/krita/Gray-D50-elle-V2-g18.icc
/usr/share/color/icc/krita/Gray-D50-elle-V2-g22.icc
/usr/share/color/icc/krita/Gray-D50-elle-V2-labl.icc
/usr/share/color/icc/krita/Gray-D50-elle-V2-rec709.icc
/usr/share/color/icc/krita/Gray-D50-elle-V2-srgbtrc.icc
/usr/share/color/icc/krita/Gray-D50-elle-V4-g10.icc
/usr/share/color/icc/krita/Gray-D50-elle-V4-g18.icc
/usr/share/color/icc/krita/Gray-D50-elle-V4-g22.icc
/usr/share/color/icc/krita/Gray-D50-elle-V4-labl.icc
/usr/share/color/icc/krita/Gray-D50-elle-V4-rec709.icc
/usr/share/color/icc/krita/Gray-D50-elle-V4-srgbtrc.icc
/usr/share/color/icc/krita/ITUR_2100_PQ_FULL.ICC
/usr/share/color/icc/krita/Lab-D50-Identity-elle-V2.icc
/usr/share/color/icc/krita/Lab-D50-Identity-elle-V4.icc
/usr/share/color/icc/krita/LargeRGB-elle-V2-g22.icc
/usr/share/color/icc/krita/README
/usr/share/color/icc/krita/Rec2020-elle-V4-g10.icc
/usr/share/color/icc/krita/WideRGB-elle-V2-g22.icc
/usr/share/color/icc/krita/XYZ-D50-Identity-elle-V4.icc
/usr/share/color/icc/krita/cmyk.icm
/usr/share/color/icc/krita/krita25_lcms-builtin-sRGB_g100-truegamma.icc
/usr/share/color/icc/krita/sRGB-elle-V2-g10.icc
/usr/share/color/icc/krita/sRGB-elle-V2-srgbtrc.icc
/usr/share/color/icc/krita/scRGB.icm
/usr/share/icons/hicolor/1024x1024/apps/krita.png
/usr/share/icons/hicolor/1024x1024/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/128x128/apps/krita.png
/usr/share/icons/hicolor/128x128/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/16x16/apps/krita.png
/usr/share/icons/hicolor/16x16/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/22x22/apps/krita.png
/usr/share/icons/hicolor/22x22/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/256x256/apps/krita.png
/usr/share/icons/hicolor/256x256/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/32x32/apps/krita.png
/usr/share/icons/hicolor/32x32/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/48x48/apps/krita.png
/usr/share/icons/hicolor/48x48/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/512x512/apps/krita.png
/usr/share/icons/hicolor/512x512/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/64x64/apps/krita.png
/usr/share/icons/hicolor/64x64/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/scalable/apps/krita.svgz
/usr/share/krita/actions/InteractionTool.action
/usr/share/krita/actions/KarbonCalligraphyTool.action
/usr/share/krita/actions/KisAssistantTool.action
/usr/share/krita/actions/KisToolCrop.action
/usr/share/krita/actions/KisToolPath.action
/usr/share/krita/actions/KisToolPencil.action
/usr/share/krita/actions/KisToolPolygon.action
/usr/share/krita/actions/KisToolPolyline.action
/usr/share/krita/actions/KisToolSelectContiguous.action
/usr/share/krita/actions/KisToolSelectElliptical.action
/usr/share/krita/actions/KisToolSelectMagnetic.action
/usr/share/krita/actions/KisToolSelectOutline.action
/usr/share/krita/actions/KisToolSelectPath.action
/usr/share/krita/actions/KisToolSelectPolygonal.action
/usr/share/krita/actions/KisToolSelectRectangular.action
/usr/share/krita/actions/KisToolSelectSimilar.action
/usr/share/krita/actions/KisToolTransform.action
/usr/share/krita/actions/MoveTool.action
/usr/share/krita/actions/PathTool.action
/usr/share/krita/actions/SvgTextTool.action
/usr/share/krita/actions/krita.action
/usr/share/krita/actions/kritamenu.action
/usr/share/krita/actions/plugin_importer.action
/usr/share/krita/actions/tenbrushes.action
/usr/share/krita/actions/tenscripts.action
/usr/share/krita/actions/threshold.action
/usr/share/krita/brushes/triangle.svg
/usr/share/krita/bundles/Krita_3_Default_Resources.bundle
/usr/share/krita/bundles/Krita_4_Default_Resources.bundle
/usr/share/krita/bundles/Krita_Artists_SeExpr_examples.bundle
/usr/share/krita/bundles/README
/usr/share/krita/bundles/RGBA_brushes.bundle
/usr/share/krita/defaultpresets/colorsmudge.kpp
/usr/share/krita/defaultpresets/complex.kpp
/usr/share/krita/defaultpresets/curvebrush.kpp
/usr/share/krita/defaultpresets/deformbrush.kpp
/usr/share/krita/defaultpresets/duplicate.kpp
/usr/share/krita/defaultpresets/dynabrush.kpp
/usr/share/krita/defaultpresets/eraser.kpp
/usr/share/krita/defaultpresets/experimentbrush.kpp
/usr/share/krita/defaultpresets/filter.kpp
/usr/share/krita/defaultpresets/gridbrush.kpp
/usr/share/krita/defaultpresets/hairybrush.kpp
/usr/share/krita/defaultpresets/hatchingbrush.kpp
/usr/share/krita/defaultpresets/paintbrush.kpp
/usr/share/krita/defaultpresets/particlebrush.kpp
/usr/share/krita/defaultpresets/roundmarker.kpp
/usr/share/krita/defaultpresets/sketchbrush.kpp
/usr/share/krita/defaultpresets/smudge.kpp
/usr/share/krita/defaultpresets/spraybrush.kpp
/usr/share/krita/defaultpresets/tangentnormal.kpp
/usr/share/krita/donation/banner.png
/usr/share/krita/dtd/krita.dtd
/usr/share/krita/gamutmasks/Atmosphere_With_Accent.kgm
/usr/share/krita/gamutmasks/Atmospheric_Triad.kgm
/usr/share/krita/gamutmasks/Complementary.kgm
/usr/share/krita/gamutmasks/Dominant_Hue_With_Accent.kgm
/usr/share/krita/gamutmasks/GamutMaskTemplate.kra
/usr/share/krita/gamutmasks/Shifted_Triad.kgm
/usr/share/krita/gamutmasks/Split_Complementary.kgm
/usr/share/krita/gamutmasks/empty_mask_preview.png
/usr/share/krita/gradients/BG-Krita2.ggr
/usr/share/krita/gradients/GPS-FG-Glare.ggr
/usr/share/krita/gradients/GPS-Fire-Blueish.ggr
/usr/share/krita/gradients/GPS-Fire-Burning-Cloud.ggr
/usr/share/krita/gradients/GPS-Fire-Dust-Blended.ggr
/usr/share/krita/gradients/GPS-Fire-Dust.ggr
/usr/share/krita/gradients/GPS-Fire-Incandescent.ggr
/usr/share/krita/gradients/GPS-Fire-Life-Span.ggr
/usr/share/krita/gradients/GPS-Haze-and-Atmosphere.ggr
/usr/share/krita/gradients/GPS-Light-Saber-_Use-FG-color_.ggr
/usr/share/krita/gradients/GPS-Nature-Pure-greens.ggr
/usr/share/krita/gradients/GPS-Nature-browns-copy.ggr
/usr/share/krita/gradients/GPS-Nature-random-greens.ggr
/usr/share/krita/gradients/GPS-Nature_Grass.ggr
/usr/share/krita/gradients/GPS-Simple-Smoke.ggr
/usr/share/krita/gradients/GPS-Steel-Bars.ggr
/usr/share/krita/gradients/GPS-eye-_Blue_.ggr
/usr/share/krita/images/krita-colorsmudge.png
/usr/share/krita/images/krita-curve.png
/usr/share/krita/images/krita-deform.png
/usr/share/krita/images/krita-duplicate.png
/usr/share/krita/images/krita-eraser.png
/usr/share/krita/images/krita-experiment.png
/usr/share/krita/images/krita-filterop.png
/usr/share/krita/images/krita-grid.png
/usr/share/krita/images/krita-hatching.png
/usr/share/krita/images/krita-paintbrush.png
/usr/share/krita/images/krita-particle.png
/usr/share/krita/images/krita-sketch.png
/usr/share/krita/images/krita-spray.png
/usr/share/krita/images/krita-sumi.png
/usr/share/krita/images/krita-tangentnormal-preview.png
/usr/share/krita/images/krita-tangentnormal.png
/usr/share/krita/images/krita_roundmarkerop.svg
/usr/share/krita/input/kritadefault.profile
/usr/share/krita/input/painttoolsaicompatible.profile
/usr/share/krita/input/photoshopcompatible.profile
/usr/share/krita/metadata/schemas/dc.schema
/usr/share/krita/metadata/schemas/exif.schema
/usr/share/krita/metadata/schemas/exrchannels.schema
/usr/share/krita/metadata/schemas/mkn.schema
/usr/share/krita/metadata/schemas/tiff.schema
/usr/share/krita/metadata/schemas/xmp.schema
/usr/share/krita/metadata/schemas/xmpmm.schema
/usr/share/krita/metadata/schemas/xmprights.schema
/usr/share/krita/paintoppresets/a)_Eraser_Circle.kpp
/usr/share/krita/paintoppresets/b)_Basic-5_Size_default.kpp
/usr/share/krita/paintoppresets/j)_WaterC_Basic_Lines-Dry.kpp
/usr/share/krita/paintoppresets/j)_WaterC_Basic_Lines-Wet-Pattern.kpp
/usr/share/krita/paintoppresets/j)_WaterC_Basic_Lines-Wet.kpp
/usr/share/krita/paintoppresets/j)_WaterC_Basic_Round-Fringe_02.kpp
/usr/share/krita/paintoppresets/j)_WaterC_Basic_Round-Grain.kpp
/usr/share/krita/paintoppresets/j)_WaterC_Basic_Round-Grunge.kpp
/usr/share/krita/paintoppresets/j)_WaterC_Flat_Big-Grain_Tilt.kpp
/usr/share/krita/paintoppresets/j)_WaterC_Flat_Decay_Tilt.kpp
/usr/share/krita/paintoppresets/j)_WaterC_Special_Blobs.kpp
/usr/share/krita/paintoppresets/j)_WaterC_Special_Splats.kpp
/usr/share/krita/paintoppresets/j)_WaterC_Spread-Pattern.kpp
/usr/share/krita/paintoppresets/j)_WaterC_Spread.kpp
/usr/share/krita/paintoppresets/j)_WaterC_Spread_WideArea.kpp
/usr/share/krita/paintoppresets/j)_WaterC_Water-Pattern.kpp
/usr/share/krita/palettes/concept-cookie.gpl
/usr/share/krita/palettes/default.gpl
/usr/share/krita/palettes/gradient.gpl
/usr/share/krita/palettes/marker.gpl
/usr/share/krita/palettes/pixelart-16.gpl
/usr/share/krita/palettes/pixelart-32.gpl
/usr/share/krita/palettes/ps.gpl
/usr/share/krita/palettes/swatch-cmyk.gpl
/usr/share/krita/palettes/swatch-colored-grey.gpl
/usr/share/krita/palettes/swatch-rgb.gpl
/usr/share/krita/palettes/swatche.gpl
/usr/share/krita/palettes/web.gpl
/usr/share/krita/patterns/01_canvas.png
/usr/share/krita/patterns/02_rough-canvas.png
/usr/share/krita/patterns/02b_WoofTissue.png
/usr/share/krita/patterns/03_default-paper.png
/usr/share/krita/patterns/04_paper-C-grain.png
/usr/share/krita/patterns/05_paper-torchon.png
/usr/share/krita/patterns/06_hard-grain.png
/usr/share/krita/patterns/08_bump-relief.png
/usr/share/krita/patterns/09_drawed_crosshatched.png
/usr/share/krita/patterns/09b_drawed-CrossedLines.png
/usr/share/krita/patterns/10_drawed_dotted.png
/usr/share/krita/patterns/11_drawed_furry.png
/usr/share/krita/patterns/12_drawed_vertical.png
/usr/share/krita/patterns/13_drawed_swirl.png
/usr/share/krita/patterns/14_texture-rock.png
/usr/share/krita/patterns/15_texture-rockB.png
/usr/share/krita/patterns/16_texture-woody.png
/usr/share/krita/patterns/17_texture-melt.png
/usr/share/krita/patterns/18_texture-bark.png
/usr/share/krita/patterns/18b_WaveFlex.png
/usr/share/krita/patterns/19_texture-crackle.png
/usr/share/krita/patterns/20_texture-vegetal.png
/usr/share/krita/patterns/21_texture-chainmail.png
/usr/share/krita/patterns/22_texture-reptile.png
/usr/share/krita/patterns/23-dynamic-screentone-A.png
/usr/share/krita/patterns/24-dynamic-screentone-B.png
/usr/share/krita/patterns/25-dynamic-screentone-C.png
/usr/share/krita/patterns/26_brush-marks.png
/usr/share/krita/patterns/Abstract_lines.png
/usr/share/krita/patterns/Cross01.pat
/usr/share/krita/patterns/Cross02.pat
/usr/share/krita/patterns/Cross03.pat
/usr/share/krita/patterns/Cross04.pat
/usr/share/krita/patterns/Cross05.pat
/usr/share/krita/patterns/Cross06.pat
/usr/share/krita/patterns/Cross07.pat
/usr/share/krita/patterns/Crumpled_Paper.pat
/usr/share/krita/patterns/DITH_0202_CLUS.pat
/usr/share/krita/patterns/DITH_0202_GEN_.pat
/usr/share/krita/patterns/DITH_0202_HORZ.pat
/usr/share/krita/patterns/DITH_0202_VERT.pat
/usr/share/krita/patterns/DITH_0404_ALT_.pat
/usr/share/krita/patterns/DITH_0404_BL22.pat
/usr/share/krita/patterns/DITH_0404_CLUS.pat
/usr/share/krita/patterns/DITH_0404_CURL.pat
/usr/share/krita/patterns/DITH_0404_DIAG.pat
/usr/share/krita/patterns/DITH_0404_ELL2.pat
/usr/share/krita/patterns/DITH_0404_ELL3.pat
/usr/share/krita/patterns/DITH_0404_ELLS.pat
/usr/share/krita/patterns/DITH_0404_GEN_.pat
/usr/share/krita/patterns/DITH_0404_HORZ.pat
/usr/share/krita/patterns/DITH_0404_SHUR.pat
/usr/share/krita/patterns/DITH_0404_SLIC.pat
/usr/share/krita/patterns/DITH_0404_VERT.pat
/usr/share/krita/patterns/DITH_0404_WAV2.pat
/usr/share/krita/patterns/DITH_0404_WAVE.pat
/usr/share/krita/patterns/DITH_0404_ZORO.pat
/usr/share/krita/patterns/DITH_0808_BL22.pat
/usr/share/krita/patterns/DITH_0808_BL22_v.pat
/usr/share/krita/patterns/DITH_0808_BUBL.pat
/usr/share/krita/patterns/DITH_0808_CIRC.pat
/usr/share/krita/patterns/DITH_0808_CLUS.pat
/usr/share/krita/patterns/DITH_0808_DIAM.pat
/usr/share/krita/patterns/DITH_0808_PANL.pat
/usr/share/krita/patterns/DITH_0808_SPOT.pat
/usr/share/krita/patterns/DITH_0808_SWRL.pat
/usr/share/krita/patterns/DITH_0808_WAVE.pat
/usr/share/krita/patterns/DITH_3232_CSTR.pat
/usr/share/krita/patterns/Grid01.pat
/usr/share/krita/patterns/Grid02.pat
/usr/share/krita/patterns/Grid03.pat
/usr/share/krita/patterns/Grid04.pat
/usr/share/krita/patterns/Grid05.pat
/usr/share/krita/patterns/HR_PastelPaper_02.pat
/usr/share/krita/patterns/HR_Wall_Paper.pat
/usr/share/krita/patterns/Maze_lines.png
/usr/share/krita/patterns/Pattern01.pat
/usr/share/krita/patterns/Pattern02.pat
/usr/share/krita/patterns/Pattern03.pat
/usr/share/krita/patterns/Pattern04.pat
/usr/share/krita/patterns/Pattern05.pat
/usr/share/krita/patterns/Pattern06.pat
/usr/share/krita/patterns/Rough_Paper.png
/usr/share/krita/patterns/Rough_Wall_With_Impasto.png
/usr/share/krita/patterns/Sand_fine.png
/usr/share/krita/patterns/Squares01.pat
/usr/share/krita/patterns/Squares02.pat
/usr/share/krita/patterns/Squares03.pat
/usr/share/krita/patterns/Squares04.pat
/usr/share/krita/patterns/Squares05.pat
/usr/share/krita/patterns/Squares06.pat
/usr/share/krita/patterns/Squares07.pat
/usr/share/krita/patterns/Squares08.pat
/usr/share/krita/patterns/Squares09.pat
/usr/share/krita/patterns/Squares10.pat
/usr/share/krita/patterns/Stars_Sized.png
/usr/share/krita/patterns/Stripes02.pat
/usr/share/krita/patterns/Stripes03.pat
/usr/share/krita/patterns/Stripes04.pat
/usr/share/krita/patterns/Stripes05.pat
/usr/share/krita/patterns/Stripes06.pat
/usr/share/krita/patterns/Stripes07.pat
/usr/share/krita/patterns/Stripes08.pat
/usr/share/krita/patterns/Stripes09.pat
/usr/share/krita/patterns/Zigzag01.pat
/usr/share/krita/patterns/Zigzag02.pat
/usr/share/krita/patterns/Zigzag03.pat
/usr/share/krita/patterns/Zigzag04.pat
/usr/share/krita/patterns/fractal_pattern.pat
/usr/share/krita/patterns/generic_paper1.pat
/usr/share/krita/patterns/generic_paper2.pat
/usr/share/krita/patterns/hexacolBW__2.pat
/usr/share/krita/pics/dark_arrow_east.png
/usr/share/krita/pics/dark_arrow_north.png
/usr/share/krita/pics/dark_arrow_north_east.png
/usr/share/krita/pics/dark_arrow_north_west.png
/usr/share/krita/pics/dark_arrow_south.png
/usr/share/krita/pics/dark_arrow_south_east.png
/usr/share/krita/pics/dark_arrow_south_west.png
/usr/share/krita/pics/dark_arrow_west.png
/usr/share/krita/pics/dark_krita_tool_assistant.png
/usr/share/krita/pics/dark_template_DIN_A3_landscape.png
/usr/share/krita/pics/dark_template_DIN_A4_portrait.png
/usr/share/krita/pics/dark_template_animation.png
/usr/share/krita/pics/dark_template_comics_empty.png
/usr/share/krita/pics/dark_template_dslr.png
/usr/share/krita/pics/dark_template_ratio_1610.png
/usr/share/krita/pics/dark_template_ratio_2391.png
/usr/share/krita/pics/dark_template_ratio_43.png
/usr/share/krita/pics/dark_template_texture.png
/usr/share/krita/pics/dark_template_web_design.png
/usr/share/krita/pics/extended_color_selector.png
/usr/share/krita/pics/kis_colselng_color_patches.png
/usr/share/krita/pics/kis_colselng_color_triangle.png
/usr/share/krita/pics/kis_colselng_my_paint_shade_selector.png
/usr/share/krita/pics/krita_tool_assistant.png
/usr/share/krita/pics/light_arrow_east.png
/usr/share/krita/pics/light_arrow_north.png
/usr/share/krita/pics/light_arrow_north_east.png
/usr/share/krita/pics/light_arrow_north_west.png
/usr/share/krita/pics/light_arrow_south.png
/usr/share/krita/pics/light_arrow_south_east.png
/usr/share/krita/pics/light_arrow_south_west.png
/usr/share/krita/pics/light_arrow_west.png
/usr/share/krita/pics/light_krita_tool_assistant.png
/usr/share/krita/pics/light_template_DIN_A3_landscape.png
/usr/share/krita/pics/light_template_DIN_A4_portrait.png
/usr/share/krita/pics/light_template_animation.png
/usr/share/krita/pics/light_template_comics_empty.png
/usr/share/krita/pics/light_template_dslr.png
/usr/share/krita/pics/light_template_ratio_1610.png
/usr/share/krita/pics/light_template_ratio_2391.png
/usr/share/krita/pics/light_template_ratio_43.png
/usr/share/krita/pics/light_template_texture.png
/usr/share/krita/pics/light_template_web_design.png
/usr/share/krita/predefined_image_sizes/A3__300_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/A3__600_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/A4__300_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/A4__600_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/A5__300_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/A5__600_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/A6__300_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/A6__600_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/Texture_1024x1024.predefinedimage
/usr/share/krita/predefined_image_sizes/Texture_2048x2048.predefinedimage
/usr/share/krita/predefined_image_sizes/Texture_256x256.predefinedimage
/usr/share/krita/predefined_image_sizes/Texture_4096x4096.predefinedimage
/usr/share/krita/predefined_image_sizes/Texture_512x512.predefinedimage
/usr/share/krita/predefined_image_sizes/US_Legal__300_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/US_Letter__300_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/US_Tabloid__300_ppi_.predefinedimage
/usr/share/krita/preset_icons/background.png
/usr/share/krita/preset_icons/emblem_icons/addition.png
/usr/share/krita/preset_icons/emblem_icons/color.png
/usr/share/krita/preset_icons/emblem_icons/comic.png
/usr/share/krita/preset_icons/emblem_icons/edit-pen.png
/usr/share/krita/preset_icons/emblem_icons/emblem_angle_10.png
/usr/share/krita/preset_icons/emblem_icons/emblem_angle_15.png
/usr/share/krita/preset_icons/emblem_icons/emblem_angle_30.png
/usr/share/krita/preset_icons/emblem_icons/emblem_angle_45.png
/usr/share/krita/preset_icons/emblem_icons/emblem_angle_60.png
/usr/share/krita/preset_icons/emblem_icons/emblem_angle_75.png
/usr/share/krita/preset_icons/emblem_icons/emblem_angle_90.png
/usr/share/krita/preset_icons/emblem_icons/emblem_rotation.png
/usr/share/krita/preset_icons/emblem_icons/emblem_tilt.png
/usr/share/krita/preset_icons/emblem_icons/experimental.png
/usr/share/krita/preset_icons/emblem_icons/favorite.png
/usr/share/krita/preset_icons/emblem_icons/love.png
/usr/share/krita/preset_icons/emblem_icons/mechanical.png
/usr/share/krita/preset_icons/emblem_icons/mouse.png
/usr/share/krita/preset_icons/emblem_icons/multidirection.png
/usr/share/krita/preset_icons/emblem_icons/question.png
/usr/share/krita/preset_icons/emblem_icons/sketch.png
/usr/share/krita/preset_icons/emblem_icons/wet.png
/usr/share/krita/preset_icons/emblem_icons/whirlpool.png
/usr/share/krita/preset_icons/tool_icons/00_01_eraser-mechanical.png
/usr/share/krita/preset_icons/tool_icons/00_02_eraser-large.png
/usr/share/krita/preset_icons/tool_icons/00_03_eraser-hard.png
/usr/share/krita/preset_icons/tool_icons/00_04_eraser-kneaded.png
/usr/share/krita/preset_icons/tool_icons/01_01_mechanical-pencil.png
/usr/share/krita/preset_icons/tool_icons/01_01_pencil-black-stone.png
/usr/share/krita/preset_icons/tool_icons/01_02_pencil-double-ring.png
/usr/share/krita/preset_icons/tool_icons/01_04_graphite.png
/usr/share/krita/preset_icons/tool_icons/02_01_charcoal-pencil-thin.png
/usr/share/krita/preset_icons/tool_icons/02_02_charcoal-pencil-medium.png
/usr/share/krita/preset_icons/tool_icons/02_03_charcoal-pencil-large.png
/usr/share/krita/preset_icons/tool_icons/02_04_charcoal-block.png
/usr/share/krita/preset_icons/tool_icons/03_01colored-pencil.png
/usr/share/krita/preset_icons/tool_icons/03_02_chalk-square.png
/usr/share/krita/preset_icons/tool_icons/03_03_pastel.png
/usr/share/krita/preset_icons/tool_icons/04_01_technical-pen.png
/usr/share/krita/preset_icons/tool_icons/04_02_gel-pen.png
/usr/share/krita/preset_icons/tool_icons/04_03_inking_fine-line_tiny.png
/usr/share/krita/preset_icons/tool_icons/04_04_inking_fine-line_medium.png
/usr/share/krita/preset_icons/tool_icons/04_05_ink-pen-atom.png
/usr/share/krita/preset_icons/tool_icons/04_06_ink-G-pen.png
/usr/share/krita/preset_icons/tool_icons/04_07_inking_dynamic_pen.png
/usr/share/krita/preset_icons/tool_icons/04_08_inking_dynamic_pen_though.png
/usr/share/krita/preset_icons/tool_icons/04_09_inking_pen_bumpy.png
/usr/share/krita/preset_icons/tool_icons/04_10_inking_pen_bumpy_though.png
/usr/share/krita/preset_icons/tool_icons/04_11_inking_pen_calligraphic.png
/usr/share/krita/preset_icons/tool_icons/04_12_rigger-brush.png
/usr/share/krita/preset_icons/tool_icons/04_13_inking_brush.png
/usr/share/krita/preset_icons/tool_icons/04_14_inking_brush_blurry.png
/usr/share/krita/preset_icons/tool_icons/04_15_ink-brush.png
/usr/share/krita/preset_icons/tool_icons/04_16_large-rounded-cut.png
/usr/share/krita/preset_icons/tool_icons/04_17_ink-pen-glass.png
/usr/share/krita/preset_icons/tool_icons/05_01_airbrush.png
/usr/share/krita/preset_icons/tool_icons/05_02_thin-stylus-tablet.png
/usr/share/krita/preset_icons/tool_icons/05_03_stylus-white.png
/usr/share/krita/preset_icons/tool_icons/05_04_stylus.png
/usr/share/krita/preset_icons/tool_icons/05_05_stylus-colored-ring.png
/usr/share/krita/preset_icons/tool_icons/05_06_stylus-colored.png
/usr/share/krita/preset_icons/tool_icons/05_07_stylus-experimental.png
/usr/share/krita/preset_icons/tool_icons/06_01_marker.png
/usr/share/krita/preset_icons/tool_icons/06_02_marker-old.png
/usr/share/krita/preset_icons/tool_icons/06_03_marker-large.png
/usr/share/krita/preset_icons/tool_icons/06_04_round_marker_detail.png
/usr/share/krita/preset_icons/tool_icons/06_05_sketching_wide_47.png
/usr/share/krita/preset_icons/tool_icons/06_06_sketching_wide_bristles.png
/usr/share/krita/preset_icons/tool_icons/07_01_synthetic-thin.png
/usr/share/krita/preset_icons/tool_icons/07_02_synthetic-medium.png
/usr/share/krita/preset_icons/tool_icons/07_03_synthetic-filbert.png
/usr/share/krita/preset_icons/tool_icons/07_04_synthetic-large-bright.png
/usr/share/krita/preset_icons/tool_icons/07_05_synthetic-large-bright-used.png
/usr/share/krita/preset_icons/tool_icons/07_06_oil-filbert.png
/usr/share/krita/preset_icons/tool_icons/07_07_oil-flat-large.png
/usr/share/krita/preset_icons/tool_icons/07_08_acrylic-rounded-used.png
/usr/share/krita/preset_icons/tool_icons/07_09_acrylic-angled.png
/usr/share/krita/preset_icons/tool_icons/07_10_acrylic-flat.png
/usr/share/krita/preset_icons/tool_icons/07_11_acrylic-mop.png
/usr/share/krita/preset_icons/tool_icons/07_12_wide_dull_round.png
/usr/share/krita/preset_icons/tool_icons/07_13_wide_brush_blurry.png
/usr/share/krita/preset_icons/tool_icons/07_14_watercolor-flat.png
/usr/share/krita/preset_icons/tool_icons/07_15_acrylic-fan-used.png
/usr/share/krita/preset_icons/tool_icons/07_16_acrylic-flat-old.png
/usr/share/krita/preset_icons/tool_icons/07_17_synthetic-very-old.png
/usr/share/krita/preset_icons/tool_icons/07_18_special-effect-used-brush.png
/usr/share/krita/preset_icons/tool_icons/08_01_watercolor-brush-medium.png
/usr/share/krita/preset_icons/tool_icons/08_02_oil-round-hard.png
/usr/share/krita/preset_icons/tool_icons/08_03_sumi-e.png
/usr/share/krita/preset_icons/tool_icons/08_04_wide_brush_big.png
/usr/share/krita/preset_icons/tool_icons/09_01_blending-stump.png
/usr/share/krita/preset_icons/tool_icons/09_02_blur_soft.png
/usr/share/krita/preset_icons/tool_icons/09_03_knife.png
/usr/share/krita/preset_icons/tool_icons/09_04_knife-rake.png
/usr/share/krita/preset_icons/tool_icons/09_05_paint-roller.png
/usr/share/krita/preset_icons/tool_icons/10_01_color-effect.png
/usr/share/krita/preset_icons/tool_icons/10_02_adjustement-contrast.png
/usr/share/krita/preset_icons/tool_icons/10_03_adjustement-dark.png
/usr/share/krita/preset_icons/tool_icons/10_04_filter.png
/usr/share/krita/preset_icons/tool_icons/10_05_deform.png
/usr/share/krita/preset_icons/tool_icons/10_06_clone.png
/usr/share/krita/preset_icons/tool_icons/11_01_wand.png
/usr/share/krita/preset_icons/tool_icons/11_02_shape.png
/usr/share/krita/preset_icons/tool_icons/11_03_experimental.png
/usr/share/krita/preset_icons/tool_icons/11_03stamp.png
/usr/share/krita/preset_icons/tool_icons/11_04_texture-indicator.png
/usr/share/krita/preset_icons/tool_icons/11_05_screentone-indicator.png
/usr/share/krita/preset_icons/tool_icons/11_06_grid.png
/usr/share/krita/preset_icons/tool_icons/12_01_Mechanical_Pencil.png
/usr/share/krita/preset_icons/tool_icons/12_02_Fineliner.png
/usr/share/krita/preset_icons/tool_icons/12_03_Marker_Permanent.png
/usr/share/krita/preset_icons/tool_icons/12_04_PenBrush_01.png
/usr/share/krita/preset_icons/tool_icons/12_05_Pen_01.png
/usr/share/krita/preset_icons/tool_icons/12_06_Pen_02.png
/usr/share/krita/preset_icons/tool_icons/12_07_Pen_03.png
/usr/share/krita/preset_icons/tool_icons/12_08_Graphite_stick.png
/usr/share/krita/preset_icons/tool_icons/12_09_Pastel_Bar_01.png
/usr/share/krita/preset_icons/tool_icons/12_10_Pastel_Bar_04.png
/usr/share/krita/preset_icons/tool_icons/12_11_Pastel_Bar_02.png
/usr/share/krita/pykrita/assignprofiledialog/Manual.html
/usr/share/krita/pykrita/assignprofiledialog/__init__.py
/usr/share/krita/pykrita/assignprofiledialog/assignprofiledialog.py
/usr/share/krita/pykrita/batch_exporter/COATools.py
/usr/share/krita/pykrita/batch_exporter/Config.py
/usr/share/krita/pykrita/batch_exporter/Infrastructure.py
/usr/share/krita/pykrita/batch_exporter/Manual.html
/usr/share/krita/pykrita/batch_exporter/Utils/Export.py
/usr/share/krita/pykrita/batch_exporter/Utils/Tree.py
/usr/share/krita/pykrita/batch_exporter/Utils/__init__.py
/usr/share/krita/pykrita/batch_exporter/__init__.py
/usr/share/krita/pykrita/batch_exporter/batch_exporter.py
/usr/share/krita/pykrita/channels2layers/Manual.html
/usr/share/krita/pykrita/channels2layers/__init__.py
/usr/share/krita/pykrita/channels2layers/channels2layers.py
/usr/share/krita/pykrita/colorspace/Manual.html
/usr/share/krita/pykrita/colorspace/__init__.py
/usr/share/krita/pykrita/colorspace/colorspace.py
/usr/share/krita/pykrita/colorspace/colorspacedialog.py
/usr/share/krita/pykrita/colorspace/components/__init__.py
/usr/share/krita/pykrita/colorspace/components/colordepthcombobox.py
/usr/share/krita/pykrita/colorspace/components/colormodelcombobox.py
/usr/share/krita/pykrita/colorspace/components/colorprofilecombobox.py
/usr/share/krita/pykrita/colorspace/resources_rc.py
/usr/share/krita/pykrita/colorspace/uicolorspace.py
/usr/share/krita/pykrita/comics_project_management_tools/LicenseList.csv
/usr/share/krita/pykrita/comics_project_management_tools/README.html
/usr/share/krita/pykrita/comics_project_management_tools/__init__.py
/usr/share/krita/pykrita/comics_project_management_tools/comics_export_dialog.py
/usr/share/krita/pykrita/comics_project_management_tools/comics_exporter.py
/usr/share/krita/pykrita/comics_project_management_tools/comics_metadata_dialog.py
/usr/share/krita/pykrita/comics_project_management_tools/comics_project_manager_docker.py
/usr/share/krita/pykrita/comics_project_management_tools/comics_project_page_viewer.py
/usr/share/krita/pykrita/comics_project_management_tools/comics_project_settings_dialog.py
/usr/share/krita/pykrita/comics_project_management_tools/comics_project_setup_wizard.py
/usr/share/krita/pykrita/comics_project_management_tools/comics_project_translation_scraper.py
/usr/share/krita/pykrita/comics_project_management_tools/comics_template_dialog.py
/usr/share/krita/pykrita/comics_project_management_tools/exporters/CPMT_ACBF_XML_Exporter.py
/usr/share/krita/pykrita/comics_project_management_tools/exporters/CPMT_CoMet_XML_Exporter.py
/usr/share/krita/pykrita/comics_project_management_tools/exporters/CPMT_Comic_Book_Info_Exporter.py
/usr/share/krita/pykrita/comics_project_management_tools/exporters/CPMT_Comic_Rack_XML_Exporter.py
/usr/share/krita/pykrita/comics_project_management_tools/exporters/CPMT_EPUB_exporter.py
/usr/share/krita/pykrita/comics_project_management_tools/exporters/CPMT_po_parser.py
/usr/share/krita/pykrita/comics_project_management_tools/exporters/__init__.py
/usr/share/krita/pykrita/comics_project_management_tools/key_format/formats.txt
/usr/share/krita/pykrita/comics_project_management_tools/key_rating/DC.csv
/usr/share/krita/pykrita/comics_project_management_tools/key_rating/FictionRatingsDotCom.csv
/usr/share/krita/pykrita/comics_project_management_tools/key_rating/Marvel.csv
/usr/share/krita/pykrita/comics_project_management_tools/projectGenLists/listA.txt
/usr/share/krita/pykrita/comics_project_management_tools/projectGenLists/listB.txt
/usr/share/krita/pykrita/documenttools/Manual.html
/usr/share/krita/pykrita/documenttools/__init__.py
/usr/share/krita/pykrita/documenttools/documenttools.py
/usr/share/krita/pykrita/documenttools/documenttoolsdialog.py
/usr/share/krita/pykrita/documenttools/tools/__init__.py
/usr/share/krita/pykrita/documenttools/tools/canvassizetool/__init__.py
/usr/share/krita/pykrita/documenttools/tools/canvassizetool/canvassizetool.py
/usr/share/krita/pykrita/documenttools/tools/rotatetool/__init__.py
/usr/share/krita/pykrita/documenttools/tools/rotatetool/rotatetool.py
/usr/share/krita/pykrita/documenttools/tools/scaletool/__init__.py
/usr/share/krita/pykrita/documenttools/tools/scaletool/scaletool.py
/usr/share/krita/pykrita/documenttools/uidocumenttools.py
/usr/share/krita/pykrita/exportlayers/Manual.html
/usr/share/krita/pykrita/exportlayers/__init__.py
/usr/share/krita/pykrita/exportlayers/exportlayers.py
/usr/share/krita/pykrita/exportlayers/exportlayersdialog.py
/usr/share/krita/pykrita/exportlayers/uiexportlayers.py
/usr/share/krita/pykrita/filtermanager/Manual.html
/usr/share/krita/pykrita/filtermanager/__init__.py
/usr/share/krita/pykrita/filtermanager/components/__init__.py
/usr/share/krita/pykrita/filtermanager/components/filtercombobox.py
/usr/share/krita/pykrita/filtermanager/components/filtermanagertreeitem.py
/usr/share/krita/pykrita/filtermanager/components/filtermanagertreemodel.py
/usr/share/krita/pykrita/filtermanager/filtermanager.py
/usr/share/krita/pykrita/filtermanager/filtermanagerdialog.py
/usr/share/krita/pykrita/filtermanager/uifiltermanager.py
/usr/share/krita/pykrita/krita_script_starter/Manual.html
/usr/share/krita/pykrita/krita_script_starter/__init__.py
/usr/share/krita/pykrita/krita_script_starter/bbdkss.ui
/usr/share/krita/pykrita/krita_script_starter/krita_script_starter.py
/usr/share/krita/pykrita/kritapykrita_assignprofiledialog.desktop
/usr/share/krita/pykrita/kritapykrita_batch_exporter.desktop
/usr/share/krita/pykrita/kritapykrita_channels2layers.desktop
/usr/share/krita/pykrita/kritapykrita_colorspace.desktop
/usr/share/krita/pykrita/kritapykrita_comics_project_management_tools.desktop
/usr/share/krita/pykrita/kritapykrita_documenttools.desktop
/usr/share/krita/pykrita/kritapykrita_exportlayers.desktop
/usr/share/krita/pykrita/kritapykrita_filtermanager.desktop
/usr/share/krita/pykrita/kritapykrita_krita_script_starter.desktop
/usr/share/krita/pykrita/kritapykrita_lastdocumentsdocker.desktop
/usr/share/krita/pykrita/kritapykrita_mixer_slider_docker.desktop
/usr/share/krita/pykrita/kritapykrita_plugin_importer.desktop
/usr/share/krita/pykrita/kritapykrita_quick_settings_docker.desktop
/usr/share/krita/pykrita/kritapykrita_scripter.desktop
/usr/share/krita/pykrita/kritapykrita_tenbrushes.desktop
/usr/share/krita/pykrita/kritapykrita_tenscripts.desktop
/usr/share/krita/pykrita/lastdocumentsdocker/Manual.html
/usr/share/krita/pykrita/lastdocumentsdocker/__init__.py
/usr/share/krita/pykrita/lastdocumentsdocker/lastdocumentsdocker.py
/usr/share/krita/pykrita/lastdocumentsdocker/lastdocumentslistmodel.py
/usr/share/krita/pykrita/mixer_slider_docker/Manual.html
/usr/share/krita/pykrita/mixer_slider_docker/__init__.py
/usr/share/krita/pykrita/mixer_slider_docker/color_slider.py
/usr/share/krita/pykrita/mixer_slider_docker/mixer_slider_docker.py
/usr/share/krita/pykrita/mixer_slider_docker/settings_dialog.py
/usr/share/krita/pykrita/mixer_slider_docker/slider_line.py
/usr/share/krita/pykrita/mixer_slider_docker/ui_mixer_slider_docker.py
/usr/share/krita/pykrita/plugin_importer/__init__.py
/usr/share/krita/pykrita/plugin_importer/manual.html
/usr/share/krita/pykrita/plugin_importer/plugin_importer.py
/usr/share/krita/pykrita/plugin_importer/plugin_importer_extension.py
/usr/share/krita/pykrita/quick_settings_docker/Manual.html
/usr/share/krita/pykrita/quick_settings_docker/__init__.py
/usr/share/krita/pykrita/quick_settings_docker/quick_settings_docker.py
/usr/share/krita/pykrita/scripter/Manual.html
/usr/share/krita/pykrita/scripter/__init__.py
/usr/share/krita/pykrita/scripter/debugcontroller.py
/usr/share/krita/pykrita/scripter/debugger_scripter/__init__.py
/usr/share/krita/pykrita/scripter/debugger_scripter/debugger.py
/usr/share/krita/pykrita/scripter/debugger_scripter/debuggerformatter.py
/usr/share/krita/pykrita/scripter/document_scripter/__init__.py
/usr/share/krita/pykrita/scripter/document_scripter/document.py
/usr/share/krita/pykrita/scripter/documentcontroller.py
/usr/share/krita/pykrita/scripter/resources_rc.py
/usr/share/krita/pykrita/scripter/scripter.py
/usr/share/krita/pykrita/scripter/scripterdialog.py
/usr/share/krita/pykrita/scripter/test.py
/usr/share/krita/pykrita/scripter/ui_scripter/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/closeaction/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/closeaction/closeaction.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/debugaction/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/debugaction/debugaction.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/newaction/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/newaction/newaction.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/openaction/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/openaction/openaction.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/reloadaction/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/reloadaction/reloadaction.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/runaction/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/runaction/docwrapper.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/runaction/runaction.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/saveaction/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/saveaction/saveaction.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/saveasaction/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/saveasaction/saveasaction.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/settingsaction/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/settingsaction/fontscombobox.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/settingsaction/settingsaction.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/settingsaction/settingsdialog.py
/usr/share/krita/pykrita/scripter/ui_scripter/actions/settingsaction/syntaxstylescombobox.py
/usr/share/krita/pykrita/scripter/ui_scripter/editor/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/editor/debugarea.py
/usr/share/krita/pykrita/scripter/ui_scripter/editor/linenumberarea.py
/usr/share/krita/pykrita/scripter/ui_scripter/editor/pythoneditor.py
/usr/share/krita/pykrita/scripter/ui_scripter/editor/statusbar.py
/usr/share/krita/pykrita/scripter/ui_scripter/syntax/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/syntax/syntax.py
/usr/share/krita/pykrita/scripter/ui_scripter/syntax/syntaxstyles.py
/usr/share/krita/pykrita/scripter/ui_scripter/tabwidgets/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/tabwidgets/debuggerwidget/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/tabwidgets/debuggerwidget/debuggertable.py
/usr/share/krita/pykrita/scripter/ui_scripter/tabwidgets/debuggerwidget/debuggerwidget.py
/usr/share/krita/pykrita/scripter/ui_scripter/tabwidgets/debuggerwidget/stepaction.py
/usr/share/krita/pykrita/scripter/ui_scripter/tabwidgets/debuggerwidget/stopaction.py
/usr/share/krita/pykrita/scripter/ui_scripter/tabwidgets/outputwidget/__init__.py
/usr/share/krita/pykrita/scripter/ui_scripter/tabwidgets/outputwidget/clearaction.py
/usr/share/krita/pykrita/scripter/ui_scripter/tabwidgets/outputwidget/outputtextedit.py
/usr/share/krita/pykrita/scripter/ui_scripter/tabwidgets/outputwidget/outputwidget.py
/usr/share/krita/pykrita/scripter/uicontroller.py
/usr/share/krita/pykrita/tenbrushes/Manual.html
/usr/share/krita/pykrita/tenbrushes/__init__.py
/usr/share/krita/pykrita/tenbrushes/dropbutton.py
/usr/share/krita/pykrita/tenbrushes/tenbrushes.py
/usr/share/krita/pykrita/tenbrushes/tenbrushesdialog.py
/usr/share/krita/pykrita/tenbrushes/uitenbrushes.py
/usr/share/krita/pykrita/tenscripts/Manual.html
/usr/share/krita/pykrita/tenscripts/__init__.py
/usr/share/krita/pykrita/tenscripts/tenscripts.py
/usr/share/krita/pykrita/tenscripts/tenscriptsdialog.py
/usr/share/krita/pykrita/tenscripts/uitenscripts.py
/usr/share/krita/qmlthemes/default/colors.js
/usr/share/krita/qmlthemes/default/fonts.js
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-Black.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-BlackIt.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-Bold.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-BoldIt.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-ExtraLight.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-ExtraLightIt.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-It.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-Light.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-LightIt.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-Regular.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-Semibold.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-SemiboldIt.otf
/usr/share/krita/qmlthemes/default/icons/A4landscape-black.svg
/usr/share/krita/qmlthemes/default/icons/A4portrait-black.svg
/usr/share/krita/qmlthemes/default/icons/add-black.svg
/usr/share/krita/qmlthemes/default/icons/add.svg
/usr/share/krita/qmlthemes/default/icons/apply-black.svg
/usr/share/krita/qmlthemes/default/icons/apply.svg
/usr/share/krita/qmlthemes/default/icons/back.svg
/usr/share/krita/qmlthemes/default/icons/camera-black.svg
/usr/share/krita/qmlthemes/default/icons/cancel-black.svg
/usr/share/krita/qmlthemes/default/icons/checkbox-checked.svg
/usr/share/krita/qmlthemes/default/icons/checkbox-unchecked.svg
/usr/share/krita/qmlthemes/default/icons/checker-small.svg
/usr/share/krita/qmlthemes/default/icons/close.svg
/usr/share/krita/qmlthemes/default/icons/color_wheel.svg
/usr/share/krita/qmlthemes/default/icons/colorpicker.svg
/usr/share/krita/qmlthemes/default/icons/combo-arrows-white.svg
/usr/share/krita/qmlthemes/default/icons/crop-black.svg
/usr/share/krita/qmlthemes/default/icons/crop.svg
/usr/share/krita/qmlthemes/default/icons/delete-black.svg
/usr/share/krita/qmlthemes/default/icons/delete.svg
/usr/share/krita/qmlthemes/default/icons/down.svg
/usr/share/krita/qmlthemes/default/icons/edit.svg
/usr/share/krita/qmlthemes/default/icons/erase.svg
/usr/share/krita/qmlthemes/default/icons/expansionmarker.svg
/usr/share/krita/qmlthemes/default/icons/fileclip-black.svg
/usr/share/krita/qmlthemes/default/icons/fileclip.svg
/usr/share/krita/qmlthemes/default/icons/filenew-black.svg
/usr/share/krita/qmlthemes/default/icons/filenew.svg
/usr/share/krita/qmlthemes/default/icons/fileopen-black.svg
/usr/share/krita/qmlthemes/default/icons/fileopen.svg
/usr/share/krita/qmlthemes/default/icons/filesave.svg
/usr/share/krita/qmlthemes/default/icons/filesaveas.svg
/usr/share/krita/qmlthemes/default/icons/fileshare.svg
/usr/share/krita/qmlthemes/default/icons/fill-black.svg
/usr/share/krita/qmlthemes/default/icons/fill.svg
/usr/share/krita/qmlthemes/default/icons/filter_delete-black.svg
/usr/share/krita/qmlthemes/default/icons/filter_load-black.svg
/usr/share/krita/qmlthemes/default/icons/filter_save-black.svg
/usr/share/krita/qmlthemes/default/icons/forward.svg
/usr/share/krita/qmlthemes/default/icons/gradient-black.svg
/usr/share/krita/qmlthemes/default/icons/gradient.svg
/usr/share/krita/qmlthemes/default/icons/help.svg
/usr/share/krita/qmlthemes/default/icons/krita_sketch.svg
/usr/share/krita/qmlthemes/default/icons/layer_clear.svg
/usr/share/krita/qmlthemes/default/icons/layer_duplicate.svg
/usr/share/krita/qmlthemes/default/icons/layer_filter-black.svg
/usr/share/krita/qmlthemes/default/icons/layer_group-black.svg
/usr/share/krita/qmlthemes/default/icons/layer_move_down.svg
/usr/share/krita/qmlthemes/default/icons/layer_move_left.svg
/usr/share/krita/qmlthemes/default/icons/layer_move_right.svg
/usr/share/krita/qmlthemes/default/icons/layer_move_up.svg
/usr/share/krita/qmlthemes/default/icons/layer_paint-black.svg
/usr/share/krita/qmlthemes/default/icons/locked_off-black.svg
/usr/share/krita/qmlthemes/default/icons/locked_off-small.svg
/usr/share/krita/qmlthemes/default/icons/locked_on-black.svg
/usr/share/krita/qmlthemes/default/icons/locked_on-small.svg
/usr/share/krita/qmlthemes/default/icons/minimize.svg
/usr/share/krita/qmlthemes/default/icons/mirror_c-black.svg
/usr/share/krita/qmlthemes/default/icons/mirror_h-black.svg
/usr/share/krita/qmlthemes/default/icons/mirror_v-black.svg
/usr/share/krita/qmlthemes/default/icons/move-black.svg
/usr/share/krita/qmlthemes/default/icons/move.svg
/usr/share/krita/qmlthemes/default/icons/paint-black.svg
/usr/share/krita/qmlthemes/default/icons/paint.svg
/usr/share/krita/qmlthemes/default/icons/palette-add-black.svg
/usr/share/krita/qmlthemes/default/icons/palette-black.svg
/usr/share/krita/qmlthemes/default/icons/palette-delete-black.svg
/usr/share/krita/qmlthemes/default/icons/palette.svg
/usr/share/krita/qmlthemes/default/icons/redo.svg
/usr/share/krita/qmlthemes/default/icons/select-add.svg
/usr/share/krita/qmlthemes/default/icons/select-apply.svg
/usr/share/krita/qmlthemes/default/icons/select-area.svg
/usr/share/krita/qmlthemes/default/icons/select-color.svg
/usr/share/krita/qmlthemes/default/icons/select-deselect.svg
/usr/share/krita/qmlthemes/default/icons/select-hide.svg
/usr/share/krita/qmlthemes/default/icons/select-intersect.svg
/usr/share/krita/qmlthemes/default/icons/select-polygon.svg
/usr/share/krita/qmlthemes/default/icons/select-rectangle.svg
/usr/share/krita/qmlthemes/default/icons/select-replace.svg
/usr/share/krita/qmlthemes/default/icons/select-reselect.svg
/usr/share/krita/qmlthemes/default/icons/select-show.svg
/usr/share/krita/qmlthemes/default/icons/select-sub.svg
/usr/share/krita/qmlthemes/default/icons/settings.svg
/usr/share/krita/qmlthemes/default/icons/switch.svg
/usr/share/krita/qmlthemes/default/icons/transform-black.svg
/usr/share/krita/qmlthemes/default/icons/transform.svg
/usr/share/krita/qmlthemes/default/icons/undo.svg
/usr/share/krita/qmlthemes/default/icons/up.svg
/usr/share/krita/qmlthemes/default/icons/visible_off-black.svg
/usr/share/krita/qmlthemes/default/icons/visible_off-small.svg
/usr/share/krita/qmlthemes/default/icons/visible_off.svg
/usr/share/krita/qmlthemes/default/icons/visible_on-black.svg
/usr/share/krita/qmlthemes/default/icons/visible_on-small.svg
/usr/share/krita/qmlthemes/default/icons/visible_on.svg
/usr/share/krita/qmlthemes/default/icons/web.svg
/usr/share/krita/qmlthemes/default/images/busyindicator.png
/usr/share/krita/qmlthemes/default/images/divider.png
/usr/share/krita/qmlthemes/default/images/header_krita_sketch.png
/usr/share/krita/qmlthemes/default/images/header_krita_sketch_light.png
/usr/share/krita/qmlthemes/default/images/kritasketch.png
/usr/share/krita/qmlthemes/default/images/shadow.png
/usr/share/krita/qmlthemes/default/sizes.js
/usr/share/krita/qmlthemes/default/theme.qml
/usr/share/krita/shortcuts/krita_default.shortcuts
/usr/share/krita/shortcuts/paint_tool_sai_compatible.shortcuts
/usr/share/krita/shortcuts/photoshop_compatible.shortcuts
/usr/share/krita/shortcuts/tablet_pro.shortcuts
/usr/share/krita/styles/markers.svg
/usr/share/krita/symbols/BalloonSymbols.svg
/usr/share/krita/symbols/pepper_carrot_speech_bubbles.svg
/usr/share/krita/symbols/preset_icons.svg
/usr/share/krita/templates/animation/.directory
/usr/share/krita/templates/animation/.source/Anim-Jp-EN.kra
/usr/share/krita/templates/animation/.source/Anim-Jp-JP.kra
/usr/share/krita/templates/animation/Anim-Jp-EN.desktop
/usr/share/krita/templates/animation/Anim-Jp-JP.desktop
/usr/share/krita/templates/comics/.directory
/usr/share/krita/templates/comics/.source/BD-EuroTemplate.kra
/usr/share/krita/templates/comics/.source/Comics-USTemplate.kra
/usr/share/krita/templates/comics/.source/Manga-JpTemplate.kra
/usr/share/krita/templates/comics/.source/a4_waffle_grid.kra
/usr/share/krita/templates/comics/BD-EuroTemplate.desktop
/usr/share/krita/templates/comics/Comics-USTemplate.desktop
/usr/share/krita/templates/comics/Manga-JpTemplate.desktop
/usr/share/krita/templates/comics/a4_waffle_grid.desktop
/usr/share/krita/templates/design/.directory
/usr/share/krita/templates/design/.source/Designcinema16_10_2484x1200_96dpiRGB_8bit_.kra
/usr/share/krita/templates/design/.source/Designcinema2.39_1_2484x1040_96dpiRGB_8bit_.kra
/usr/share/krita/templates/design/.source/DesignpresentationA3Landscape_4960x3508_300dpiRGB_8bit_.kra
/usr/share/krita/templates/design/.source/DesignpresentationA4portrait_2480x3508_300dpiRGB_8bit_.kra
/usr/share/krita/templates/design/.source/Designscreen4_3_2250x1680_96dpiRGB_8bit_.kra
/usr/share/krita/templates/design/.source/web_design.kra
/usr/share/krita/templates/design/Designcinema16_10_2484x1200_96dpiRGB_8bit_.desktop
/usr/share/krita/templates/design/Designcinema2.39_1_2484x1040_96dpiRGB_8bit_.desktop
/usr/share/krita/templates/design/DesignpresentationA3Landscape_4960x3508_300dpiRGB_8bit_.desktop
/usr/share/krita/templates/design/DesignpresentationA4portrait_2480x3508_300dpiRGB_8bit_.desktop
/usr/share/krita/templates/design/Designscreen4_3_2250x1680_96dpiRGB_8bit_.desktop
/usr/share/krita/templates/design/web_design.desktop
/usr/share/krita/templates/dslr/.directory
/usr/share/krita/templates/dslr/.source/Canon_550D_5184x3456.kra
/usr/share/krita/templates/dslr/.source/Canon_5Dmk3_5760x3840.kra
/usr/share/krita/templates/dslr/.source/Nikon_D3000_3872x2592.kra
/usr/share/krita/templates/dslr/.source/Nikon_D5000_4288x2848.kra
/usr/share/krita/templates/dslr/.source/Nikon_D7000_4928x3264.kra
/usr/share/krita/templates/dslr/Canon_550D_5184x3456.desktop
/usr/share/krita/templates/dslr/Canon_5Dmk3_5760x3840.desktop
/usr/share/krita/templates/dslr/Nikon_D3000_3872x2592.desktop
/usr/share/krita/templates/dslr/Nikon_D5000_4288x2848.desktop
/usr/share/krita/templates/dslr/Nikon_D7000_4928x3264.desktop
/usr/share/krita/templates/texture/.directory
/usr/share/krita/templates/texture/.source/Texture1024x10248bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture1k32bitscalar.kra
/usr/share/krita/templates/texture/.source/Texture1k8bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture2048x20488bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture256x2568bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture2k32bitscalar.kra
/usr/share/krita/templates/texture/.source/Texture2k8bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture4096x40968bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture4k32bitscalar.kra
/usr/share/krita/templates/texture/.source/Texture4k8bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture512x5128bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture8k32bitscalar.kra
/usr/share/krita/templates/texture/.source/Texture8k8bitsrgb.kra
/usr/share/krita/templates/texture/Texture1024x10248bitsrgb.desktop
/usr/share/krita/templates/texture/Texture1k32bitscalar.desktop
/usr/share/krita/templates/texture/Texture1k8bitsrgb.desktop
/usr/share/krita/templates/texture/Texture2048x20488bitsrgb.desktop
/usr/share/krita/templates/texture/Texture256x2568bitsrgb.desktop
/usr/share/krita/templates/texture/Texture2k32bitscalar.desktop
/usr/share/krita/templates/texture/Texture2k8bitsrgb.desktop
/usr/share/krita/templates/texture/Texture4096x40968bitsrgb.desktop
/usr/share/krita/templates/texture/Texture4k32bitscalar.desktop
/usr/share/krita/templates/texture/Texture4k8bitsrgb.desktop
/usr/share/krita/templates/texture/Texture512x5128bitsrgb.desktop
/usr/share/krita/templates/texture/Texture8k32bitscalar.desktop
/usr/share/krita/templates/texture/Texture8k8bitsrgb.desktop
"/usr/share/krita/windowlayouts/Cockpit (laptop mode).kwl"
"/usr/share/krita/windowlayouts/Dual screen editing.kwl"
/usr/share/krita/workspaces/Animation.kws
/usr/share/krita/workspaces/Big_Paint.kws
/usr/share/krita/workspaces/Big_Paint_2.kws
/usr/share/krita/workspaces/Big_Vector.kws
/usr/share/krita/workspaces/Default.kws
/usr/share/krita/workspaces/Minimal.kws
/usr/share/krita/workspaces/Small_Vector.kws
/usr/share/krita/workspaces/VFX_Paint.kws
/usr/share/kritaplugins/buginfo.xmlgui
/usr/share/kritaplugins/clonesarray.xmlgui
/usr/share/kritaplugins/colorrange.xmlgui
/usr/share/kritaplugins/colorspaceconversion.xmlgui
/usr/share/kritaplugins/imageseparate.xmlgui
/usr/share/kritaplugins/imagesize.xmlgui
/usr/share/kritaplugins/imagesplit.xmlgui
/usr/share/kritaplugins/layersplit.xmlgui
/usr/share/kritaplugins/metadataeditor.xmlgui
/usr/share/kritaplugins/metadataeditor/dublincore.xmlgui
/usr/share/kritaplugins/metadataeditor/exif.xmlgui
/usr/share/kritaplugins/modify_selection.xmlgui
/usr/share/kritaplugins/offsetimage.xmlgui
/usr/share/kritaplugins/resourcemanager.xmlgui
/usr/share/kritaplugins/rotateimage.xmlgui
/usr/share/kritaplugins/shearimage.xmlgui
/usr/share/kritaplugins/waveletdecompose.xmlgui
/usr/share/metainfo/org.kde.krita.appdata.xml
/usr/share/xdg/kritarc

%files dev
%defattr(-,root,root,-)
/usr/lib64/libkritabasicflakes.so
/usr/lib64/libkritacolor.so
/usr/lib64/libkritacolord.so
/usr/lib64/libkritacommand.so
/usr/lib64/libkritaflake.so
/usr/lib64/libkritaglobal.so
/usr/lib64/libkritaimage.so
/usr/lib64/libkritaimpex.so
/usr/lib64/libkritalibbrush.so
/usr/lib64/libkritalibkis.so
/usr/lib64/libkritalibkra.so
/usr/lib64/libkritalibpaintop.so
/usr/lib64/libkritametadata.so
/usr/lib64/libkritaodf.so
/usr/lib64/libkritapigment.so
/usr/lib64/libkritaplugin.so
/usr/lib64/libkritapsd.so
/usr/lib64/libkritaqml.so
/usr/lib64/libkritastore.so
/usr/lib64/libkritatext.so
/usr/lib64/libkritatextlayout.so
/usr/lib64/libkritaui.so
/usr/lib64/libkritaversion.so
/usr/lib64/libkritawidgets.so
/usr/lib64/libkritawidgetutils.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/krita-python-libs/PyKrita/krita.so
/usr/lib64/kritaplugins/krita_colorspaces_extensions.so
/usr/lib64/kritaplugins/krita_flaketools.so
/usr/lib64/kritaplugins/krita_karbontools.so
/usr/lib64/kritaplugins/krita_raw_import.so
/usr/lib64/kritaplugins/krita_shape_artistictext.so
/usr/lib64/kritaplugins/krita_shape_image.so
/usr/lib64/kritaplugins/krita_shape_paths.so
/usr/lib64/kritaplugins/krita_shape_text.so
/usr/lib64/kritaplugins/krita_tool_svgtext.so
/usr/lib64/kritaplugins/kritaanimationdocker.so
/usr/lib64/kritaplugins/kritaarrangedocker.so
/usr/lib64/kritaplugins/kritaartisticcolorselector.so
/usr/lib64/kritaplugins/kritaasccdl.so
/usr/lib64/kritaplugins/kritaassistanttool.so
/usr/lib64/kritaplugins/kritablurfilter.so
/usr/lib64/kritaplugins/kritabrushexport.so
/usr/lib64/kritaplugins/kritabrushimport.so
/usr/lib64/kritaplugins/kritabuginfo.so
/usr/lib64/kritaplugins/kritachanneldocker.so
/usr/lib64/kritaplugins/kritaclonesarray.so
/usr/lib64/kritaplugins/kritacolorgenerator.so
/usr/lib64/kritaplugins/kritacolorrange.so
/usr/lib64/kritaplugins/kritacolorselectorng.so
/usr/lib64/kritaplugins/kritacolorsfilters.so
/usr/lib64/kritaplugins/kritacolorsmudgepaintop.so
/usr/lib64/kritaplugins/kritacolorspaceconversion.so
/usr/lib64/kritaplugins/kritacompositiondocker.so
/usr/lib64/kritaplugins/kritaconvertheighttonormalmap.so
/usr/lib64/kritaplugins/kritaconvolutionfilters.so
/usr/lib64/kritaplugins/kritacsvexport.so
/usr/lib64/kritaplugins/kritacsvimport.so
/usr/lib64/kritaplugins/kritacurvepaintop.so
/usr/lib64/kritaplugins/kritadefaultpaintops.so
/usr/lib64/kritaplugins/kritadefaulttools.so
/usr/lib64/kritaplugins/kritadeformpaintop.so
/usr/lib64/kritaplugins/kritadigitalmixer.so
/usr/lib64/kritaplugins/kritadodgeburn.so
/usr/lib64/kritaplugins/kritaedgedetection.so
/usr/lib64/kritaplugins/kritaembossfilter.so
/usr/lib64/kritaplugins/kritaexample.so
/usr/lib64/kritaplugins/kritaexperimentpaintop.so
/usr/lib64/kritaplugins/kritaexrexport.so
/usr/lib64/kritaplugins/kritaexrimport.so
/usr/lib64/kritaplugins/kritaextensioncolorsfilters.so
/usr/lib64/kritaplugins/kritafastcolortransferfilter.so
/usr/lib64/kritaplugins/kritafilterop.so
/usr/lib64/kritaplugins/kritagamutmask.so
/usr/lib64/kritaplugins/kritagaussianhighpassfilter.so
/usr/lib64/kritaplugins/kritagradientgenerator.so
/usr/lib64/kritaplugins/kritagradientmap.so
/usr/lib64/kritaplugins/kritagriddocker.so
/usr/lib64/kritaplugins/kritagridpaintop.so
/usr/lib64/kritaplugins/kritahairypaintop.so
/usr/lib64/kritaplugins/kritahalftone.so
/usr/lib64/kritaplugins/kritahatchingpaintop.so
/usr/lib64/kritaplugins/kritaheightmapexport.so
/usr/lib64/kritaplugins/kritaheightmapimport.so
/usr/lib64/kritaplugins/kritahistogramdocker.so
/usr/lib64/kritaplugins/kritahistorydocker.so
/usr/lib64/kritaplugins/kritaimageenhancement.so
/usr/lib64/kritaplugins/kritaimagesize.so
/usr/lib64/kritaplugins/kritaimagesplit.so
/usr/lib64/kritaplugins/kritaindexcolors.so
/usr/lib64/kritaplugins/kritajp2import.so
/usr/lib64/kritaplugins/kritajpegexport.so
/usr/lib64/kritaplugins/kritajpegimport.so
/usr/lib64/kritaplugins/kritakraexport.so
/usr/lib64/kritaplugins/kritakraimport.so
/usr/lib64/kritaplugins/kritalayerdocker.so
/usr/lib64/kritaplugins/kritalayergroupswitcher.so
/usr/lib64/kritaplugins/kritalayersplit.so
/usr/lib64/kritaplugins/kritalcmsengine.so
/usr/lib64/kritaplugins/kritalevelfilter.so
/usr/lib64/kritaplugins/kritalogdocker.so
/usr/lib64/kritaplugins/kritalutdocker.so
/usr/lib64/kritaplugins/kritametadataeditor.so
/usr/lib64/kritaplugins/kritamodifyselection.so
/usr/lib64/kritaplugins/kritamultigridpatterngenerator.so
/usr/lib64/kritaplugins/kritanoisefilter.so
/usr/lib64/kritaplugins/kritanormalize.so
/usr/lib64/kritaplugins/kritaoffsetimage.so
/usr/lib64/kritaplugins/kritaoilpaintfilter.so
/usr/lib64/kritaplugins/kritaoraexport.so
/usr/lib64/kritaplugins/kritaoraimport.so
/usr/lib64/kritaplugins/kritaoverviewdocker.so
/usr/lib64/kritaplugins/kritapalettedocker.so
/usr/lib64/kritaplugins/kritapalettize.so
/usr/lib64/kritaplugins/kritaparticlepaintop.so
/usr/lib64/kritaplugins/kritapatterndocker.so
/usr/lib64/kritaplugins/kritapatterngenerator.so
/usr/lib64/kritaplugins/kritapdfimport.so
/usr/lib64/kritaplugins/kritaphongbumpmap.so
/usr/lib64/kritaplugins/kritapixelizefilter.so
/usr/lib64/kritaplugins/kritapngexport.so
/usr/lib64/kritaplugins/kritapngimport.so
/usr/lib64/kritaplugins/kritaposterize.so
/usr/lib64/kritaplugins/kritapresetdocker.so
/usr/lib64/kritaplugins/kritapresethistory.so
/usr/lib64/kritaplugins/kritapsdexport.so
/usr/lib64/kritaplugins/kritapsdimport.so
/usr/lib64/kritaplugins/kritapykrita.so
/usr/lib64/kritaplugins/kritaqimageioexport.so
/usr/lib64/kritaplugins/kritaqimageioimport.so
/usr/lib64/kritaplugins/kritaqmic.so
/usr/lib64/kritaplugins/kritaqmlexport.so
/usr/lib64/kritaplugins/kritaraindropsfilter.so
/usr/lib64/kritaplugins/kritarandompickfilter.so
/usr/lib64/kritaplugins/kritaresourcemanager.so
/usr/lib64/kritaplugins/kritarotateimage.so
/usr/lib64/kritaplugins/kritaroundcornersfilter.so
/usr/lib64/kritaplugins/kritaroundmarkerpaintop.so
/usr/lib64/kritaplugins/kritascreentonegenerator.so
/usr/lib64/kritaplugins/kritaselectiontools.so
/usr/lib64/kritaplugins/kritaseparatechannels.so
/usr/lib64/kritaplugins/kritashearimage.so
/usr/lib64/kritaplugins/kritasimplexnoisegenerator.so
/usr/lib64/kritaplugins/kritasketchpaintop.so
/usr/lib64/kritaplugins/kritasmallcolorselector.so
/usr/lib64/kritaplugins/kritasmalltilesfilter.so
/usr/lib64/kritaplugins/kritasnapshotdocker.so
/usr/lib64/kritaplugins/kritaspecificcolorselector.so
/usr/lib64/kritaplugins/kritaspraypaintop.so
/usr/lib64/kritaplugins/kritaspriterexport.so
/usr/lib64/kritaplugins/kritasvgcollectiondocker.so
/usr/lib64/kritaplugins/kritasvgimport.so
/usr/lib64/kritaplugins/kritatangentnormalpaintop.so
/usr/lib64/kritaplugins/kritatasksetdocker.so
/usr/lib64/kritaplugins/kritatgaexport.so
/usr/lib64/kritaplugins/kritatgaimport.so
/usr/lib64/kritaplugins/kritathreshold.so
/usr/lib64/kritaplugins/kritatiffexport.so
/usr/lib64/kritaplugins/kritatiffimport.so
/usr/lib64/kritaplugins/kritatoolSmartPatch.so
/usr/lib64/kritaplugins/kritatoolcrop.so
/usr/lib64/kritaplugins/kritatooldyna.so
/usr/lib64/kritaplugins/kritatoollazybrush.so
/usr/lib64/kritaplugins/kritatoolpolygon.so
/usr/lib64/kritaplugins/kritatoolpolyline.so
/usr/lib64/kritaplugins/kritatooltransform.so
/usr/lib64/kritaplugins/kritatouchdocker.so
/usr/lib64/kritaplugins/kritaunsharpfilter.so
/usr/lib64/kritaplugins/kritawavefilter.so
/usr/lib64/kritaplugins/kritawaveletdecompose.so
/usr/lib64/kritaplugins/kritaxcfimport.so
/usr/lib64/libkritabasicflakes.so.20
/usr/lib64/libkritabasicflakes.so.20.0.0
/usr/lib64/libkritacolor.so.20
/usr/lib64/libkritacolor.so.20.0.0
/usr/lib64/libkritacolord.so.20
/usr/lib64/libkritacolord.so.20.0.0
/usr/lib64/libkritacommand.so.20
/usr/lib64/libkritacommand.so.20.0.0
/usr/lib64/libkritaflake.so.20
/usr/lib64/libkritaflake.so.20.0.0
/usr/lib64/libkritaglobal.so.20
/usr/lib64/libkritaglobal.so.20.0.0
/usr/lib64/libkritaimage.so.20
/usr/lib64/libkritaimage.so.20.0.0
/usr/lib64/libkritaimpex.so.20
/usr/lib64/libkritaimpex.so.20.0.0
/usr/lib64/libkritalibbrush.so.20
/usr/lib64/libkritalibbrush.so.20.0.0
/usr/lib64/libkritalibkis.so.20
/usr/lib64/libkritalibkis.so.20.0.0
/usr/lib64/libkritalibkra.so.20
/usr/lib64/libkritalibkra.so.20.0.0
/usr/lib64/libkritalibpaintop.so.20
/usr/lib64/libkritalibpaintop.so.20.0.0
/usr/lib64/libkritametadata.so.20
/usr/lib64/libkritametadata.so.20.0.0
/usr/lib64/libkritaodf.so.20
/usr/lib64/libkritaodf.so.20.0.0
/usr/lib64/libkritapigment.so.20
/usr/lib64/libkritapigment.so.20.0.0
/usr/lib64/libkritaplugin.so.20
/usr/lib64/libkritaplugin.so.20.0.0
/usr/lib64/libkritapsd.so.20
/usr/lib64/libkritapsd.so.20.0.0
/usr/lib64/libkritaqml.so.20
/usr/lib64/libkritaqml.so.20.0.0
/usr/lib64/libkritastore.so.20
/usr/lib64/libkritastore.so.20.0.0
/usr/lib64/libkritatext.so.20
/usr/lib64/libkritatext.so.20.0.0
/usr/lib64/libkritatextlayout.so.20
/usr/lib64/libkritatextlayout.so.20.0.0
/usr/lib64/libkritaui.so.20
/usr/lib64/libkritaui.so.20.0.0
/usr/lib64/libkritaversion.so.20
/usr/lib64/libkritaversion.so.20.0.0
/usr/lib64/libkritawidgets.so.20
/usr/lib64/libkritawidgets.so.20.0.0
/usr/lib64/libkritawidgetutils.so.20
/usr/lib64/libkritawidgetutils.so.20.0.0
/usr/lib64/qt5/qml/org/krita/draganddrop/libdraganddropplugin.so
/usr/lib64/qt5/qml/org/krita/draganddrop/qmldir
/usr/lib64/qt5/qml/org/krita/sketch/components/BusyIndicator.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Button.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/CategorySwitcher.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/CheckBox.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/ColorSwatch.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Dialog.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Divider.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/DropShadow.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/ExpandingListView.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Header.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Label.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/ListItem.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/MessageStack.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/NewImageList.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/NewsList.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Page.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/PageStack.js
/usr/lib64/qt5/qml/org/krita/sketch/components/PageStack.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/PanelTextField.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/RangeCombo.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/RangeInput.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/RecentFilesList.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/ScrollDecorator.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Shadow.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Slider.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/TextField.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/TextFieldMultiline.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Tooltip.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/VirtualKeyboard.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/qmldir
/usr/lib64/qt5/qml/org/krita/sketch/libkritasketchplugin.so
/usr/lib64/qt5/qml/org/krita/sketch/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/krita/095d1f504f6fd8add73a4e4964e37f260f332b6a
/usr/share/package-licenses/krita/133efad5329acf364135c569ac01ec084c3d4647
/usr/share/package-licenses/krita/4577cbeb3556a519433c8f3b7476c74b55f7ef7a
/usr/share/package-licenses/krita/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/krita/92ebac73a2c8c52b8a305df0311eb17a025a84c2
/usr/share/package-licenses/krita/9a1929f4700d2407c70b507b3b2aaf6226a9543c
/usr/share/package-licenses/krita/b274cc52fd06db856281db3593167f8765c148c9
/usr/share/package-licenses/krita/b6f3908b5e9bfb4f93ffbd7a442bf38a75ccb44a
/usr/share/package-licenses/krita/fad0fbaf831fead007f4465821459c58a2973eb0
/usr/share/package-licenses/krita/ff3ed70db4739b3c6747c7f624fe2bad70802987

%files locales -f krita.lang
%defattr(-,root,root,-)

