#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : krita
Version  : 4.1.3.1
Release  : 1
URL      : https://github.com/KDE/krita/archive/v4.1.3.1.tar.gz
Source0  : https://github.com/KDE/krita/archive/v4.1.3.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 GPL-3.0 LGPL-2.1
Requires: krita-bin
Requires: krita-lib
Requires: krita-data
Requires: krita-license
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : buildreq-qmake
BuildRequires : eigen-dev
BuildRequires : extra-cmake-modules pkgconfig(OpenEXR)
BuildRequires : extra-cmake-modules pkgconfig(poppler)
BuildRequires : extra-cmake-modules pkgconfig(xcb) xcb-util-cursor-dev xcb-util-image-dev xcb-util-keysyms-dev xcb-util-renderutil-dev xcb-util-wm-dev xcb-util-dev
BuildRequires : git
BuildRequires : gsl-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(OpenEXR)
BuildRequires : pkgconfig(exiv2)
BuildRequires : pkgconfig(fftw3)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(libraw)
BuildRequires : pkgconfig(libraw_r)
BuildRequires : poppler-dev
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : tiff-dev
BuildRequires : zlib-dev

%description
Without introducing some artificial compatibility layers,
a native windows development environment (e.g. Visual Studio 2010)
does not know about some includes known in the UNIX world.

%package bin
Summary: bin components for the krita package.
Group: Binaries
Requires: krita-data = %{version}-%{release}
Requires: krita-license = %{version}-%{release}

%description bin
bin components for the krita package.


%package data
Summary: data components for the krita package.
Group: Data

%description data
data components for the krita package.


%package dev
Summary: dev components for the krita package.
Group: Development
Requires: krita-lib = %{version}-%{release}
Requires: krita-bin = %{version}-%{release}
Requires: krita-data = %{version}-%{release}
Provides: krita-devel = %{version}-%{release}

%description dev
dev components for the krita package.


%package lib
Summary: lib components for the krita package.
Group: Libraries
Requires: krita-data = %{version}-%{release}
Requires: krita-license = %{version}-%{release}

%description lib
lib components for the krita package.


%package license
Summary: license components for the krita package.
Group: Default

%description license
license components for the krita package.


%prep
%setup -q -n krita-4.1.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538678273
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :

%install
export SOURCE_DATE_EPOCH=1538678273
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/krita
cp COPYING %{buildroot}/usr/share/doc/krita/COPYING
cp COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/doc/krita/COPYING-CMAKE-SCRIPTS
cp cmake/modules/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/doc/krita/cmake_modules_COPYING-CMAKE-SCRIPTS
cp krita/data/aboutdata/LICENSE %{buildroot}/usr/share/doc/krita/krita_data_aboutdata_LICENSE
cp krita/integration/LICENSE %{buildroot}/usr/share/doc/krita/krita_integration_LICENSE
cp krita/integration/kritaquicklook/LICENSE %{buildroot}/usr/share/doc/krita/krita_integration_kritaquicklook_LICENSE
cp packaging/windows/installer/license_gpl-3.0.rtf %{buildroot}/usr/share/doc/krita/packaging_windows_installer_license_gpl-3.0.rtf
cp plugins/impex/raw/3rdparty/libkdcraw/COPYING %{buildroot}/usr/share/doc/krita/plugins_impex_raw_3rdparty_libkdcraw_COPYING
cp plugins/impex/raw/3rdparty/libkdcraw/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/doc/krita/plugins_impex_raw_3rdparty_libkdcraw_COPYING-CMAKE-SCRIPTS
cp plugins/impex/raw/3rdparty/libkdcraw/COPYING.LIB %{buildroot}/usr/share/doc/krita/plugins_impex_raw_3rdparty_libkdcraw_COPYING.LIB
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/krita

%files data
%defattr(-,root,root,-)
/usr/share/applications/krita_brush.desktop
/usr/share/applications/krita_csv.desktop
/usr/share/applications/krita_exr.desktop
/usr/share/applications/krita_heightmap.desktop
/usr/share/applications/krita_jpeg.desktop
/usr/share/applications/krita_kra.desktop
/usr/share/applications/krita_ora.desktop
/usr/share/applications/krita_png.desktop
/usr/share/applications/krita_ppm.desktop
/usr/share/applications/krita_psd.desktop
/usr/share/applications/krita_qimageio.desktop
/usr/share/applications/krita_raw.desktop
/usr/share/applications/krita_spriter.desktop
/usr/share/applications/krita_svg.desktop
/usr/share/applications/krita_tga.desktop
/usr/share/applications/krita_tiff.desktop
/usr/share/applications/krita_xcf.desktop
/usr/share/applications/org.kde.krita.desktop
/usr/share/color-schemes/KritaBlender.colors
/usr/share/color-schemes/KritaBright.colors
/usr/share/color-schemes/KritaDark.colors
/usr/share/color-schemes/KritaDarker.colors
/usr/share/color-schemes/KritaNeutral.colors
/usr/share/color/icc/krita/ACEScg-elle-V4-g10.icc
/usr/share/color/icc/krita/ClayRGB-elle-V4-srgbtrc.icc
/usr/share/color/icc/krita/Gray-D50-elle-V2-g10.icc
/usr/share/color/icc/krita/Gray-D50-elle-V2-g18.icc
/usr/share/color/icc/krita/Gray-D50-elle-V2-g22.icc
/usr/share/color/icc/krita/Gray-D50-elle-V2-labl.icc
/usr/share/color/icc/krita/Gray-D50-elle-V2-rec709.icc
/usr/share/color/icc/krita/Gray-D50-elle-V2-srgbtrc.icc
/usr/share/color/icc/krita/Gray-D50-elle-V4-g10.icc
/usr/share/color/icc/krita/Gray-D50-elle-V4-g18.icc
/usr/share/color/icc/krita/Gray-D50-elle-V4-g22.icc
/usr/share/color/icc/krita/Gray-D50-elle-V4-labl.icc
/usr/share/color/icc/krita/Gray-D50-elle-V4-rec709.icc
/usr/share/color/icc/krita/Gray-D50-elle-V4-srgbtrc.icc
/usr/share/color/icc/krita/Lab-D50-Identity-elle-V2.icc
/usr/share/color/icc/krita/Lab-D50-Identity-elle-V4.icc
/usr/share/color/icc/krita/README
/usr/share/color/icc/krita/XYZ-D50-Identity-elle-V4.icc
/usr/share/color/icc/krita/cmyk.icm
/usr/share/color/icc/krita/krita25_lcms-builtin-sRGB_g100-truegamma.icc
/usr/share/color/icc/krita/sRGB-elle-V2-g10.icc
/usr/share/color/icc/krita/sRGB-elle-V2-srgbtrc.icc
/usr/share/color/icc/krita/scRGB.icm
/usr/share/icons/hicolor/1024x1024/apps/calligrakrita.png
/usr/share/icons/hicolor/1024x1024/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/128x128/apps/calligrakrita.png
/usr/share/icons/hicolor/128x128/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/16x16/apps/calligrakrita.png
/usr/share/icons/hicolor/16x16/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/22x22/apps/calligrakrita.png
/usr/share/icons/hicolor/22x22/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/256x256/apps/calligrakrita.png
/usr/share/icons/hicolor/256x256/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/32x32/apps/calligrakrita.png
/usr/share/icons/hicolor/32x32/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/48x48/apps/calligrakrita.png
/usr/share/icons/hicolor/48x48/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/512x512/apps/calligrakrita.png
/usr/share/icons/hicolor/512x512/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/64x64/apps/calligrakrita.png
/usr/share/icons/hicolor/64x64/mimetypes/application-x-krita.png
/usr/share/icons/hicolor/scalable/apps/calligrakrita.svgz
/usr/share/krita/actions/ConnectionTool.action
/usr/share/krita/actions/InteractionTool.action
/usr/share/krita/actions/KisAssistantTool.action
/usr/share/krita/actions/KisToolCrop.action
/usr/share/krita/actions/KisToolPath.action
/usr/share/krita/actions/KisToolPencil.action
/usr/share/krita/actions/KisToolPolygon.action
/usr/share/krita/actions/KisToolPolyline.action
/usr/share/krita/actions/KisToolSelectContiguous.action
/usr/share/krita/actions/KisToolSelectElliptical.action
/usr/share/krita/actions/KisToolSelectOutline.action
/usr/share/krita/actions/KisToolSelectPath.action
/usr/share/krita/actions/KisToolSelectPolygonal.action
/usr/share/krita/actions/KisToolSelectRectangular.action
/usr/share/krita/actions/KisToolSelectSimilar.action
/usr/share/krita/actions/KisToolTransform.action
/usr/share/krita/actions/MoveTool.action
/usr/share/krita/actions/PathTool.action
/usr/share/krita/actions/SvgTextTool.action
/usr/share/krita/actions/krita.action
/usr/share/krita/actions/kritamenu.action
/usr/share/krita/actions/threshold.action
/usr/share/krita/brushes/triangle.svg
/usr/share/krita/bundles/Krita_3_Default_Resources.bundle
/usr/share/krita/bundles/Krita_4_Default_Resources.bundle
/usr/share/krita/bundles/README
/usr/share/krita/defaultpresets/colorsmudge.kpp
/usr/share/krita/defaultpresets/complex.kpp
/usr/share/krita/defaultpresets/curvebrush.kpp
/usr/share/krita/defaultpresets/deformbrush.kpp
/usr/share/krita/defaultpresets/duplicate.kpp
/usr/share/krita/defaultpresets/dynabrush.kpp
/usr/share/krita/defaultpresets/eraser.kpp
/usr/share/krita/defaultpresets/experimentbrush.kpp
/usr/share/krita/defaultpresets/filter.kpp
/usr/share/krita/defaultpresets/gridbrush.kpp
/usr/share/krita/defaultpresets/hairybrush.kpp
/usr/share/krita/defaultpresets/hatchingbrush.kpp
/usr/share/krita/defaultpresets/paintbrush.kpp
/usr/share/krita/defaultpresets/particlebrush.kpp
/usr/share/krita/defaultpresets/roundmarker.kpp
/usr/share/krita/defaultpresets/sketchbrush.kpp
/usr/share/krita/defaultpresets/smudge.kpp
/usr/share/krita/defaultpresets/spraybrush.kpp
/usr/share/krita/defaultpresets/tangentnormal.kpp
/usr/share/krita/dtd/krita.dtd
/usr/share/krita/gamutmasks/Atmosphere_With_Accent.kgm
/usr/share/krita/gamutmasks/Atmospheric_Triad.kgm
/usr/share/krita/gamutmasks/Complementary.kgm
/usr/share/krita/gamutmasks/Dominant_Hue_With_Accent.kgm
/usr/share/krita/gamutmasks/GamutMaskTemplate.kra
/usr/share/krita/gamutmasks/Shifted_Triad.kgm
/usr/share/krita/gamutmasks/Split_Complementary.kgm
/usr/share/krita/gamutmasks/empty_mask_preview.png
/usr/share/krita/gradients/BG-Krita2.ggr
/usr/share/krita/gradients/GPS-FG-Glare.ggr
/usr/share/krita/gradients/GPS-Fire-Blueish.ggr
/usr/share/krita/gradients/GPS-Fire-Burning-Cloud.ggr
/usr/share/krita/gradients/GPS-Fire-Dust-Blended.ggr
/usr/share/krita/gradients/GPS-Fire-Dust.ggr
/usr/share/krita/gradients/GPS-Fire-Incandescent.ggr
/usr/share/krita/gradients/GPS-Fire-Life-Span.ggr
/usr/share/krita/gradients/GPS-Haze-and-Atmosphere.ggr
/usr/share/krita/gradients/GPS-Light-Saber-_Use-FG-color_.ggr
/usr/share/krita/gradients/GPS-Nature-Pure-greens.ggr
/usr/share/krita/gradients/GPS-Nature-browns-copy.ggr
/usr/share/krita/gradients/GPS-Nature-random-greens.ggr
/usr/share/krita/gradients/GPS-Nature_Grass.ggr
/usr/share/krita/gradients/GPS-Simple-Smoke.ggr
/usr/share/krita/gradients/GPS-Steel-Bars.ggr
/usr/share/krita/gradients/GPS-eye-_Blue_.ggr
/usr/share/krita/images/krita-colorsmudge.png
/usr/share/krita/images/krita-curve.png
/usr/share/krita/images/krita-deform.png
/usr/share/krita/images/krita-duplicate.png
/usr/share/krita/images/krita-eraser.png
/usr/share/krita/images/krita-experiment.png
/usr/share/krita/images/krita-filterop.png
/usr/share/krita/images/krita-grid.png
/usr/share/krita/images/krita-hatching.png
/usr/share/krita/images/krita-paintbrush.png
/usr/share/krita/images/krita-particle.png
/usr/share/krita/images/krita-sketch.png
/usr/share/krita/images/krita-spray.png
/usr/share/krita/images/krita-sumi.png
/usr/share/krita/images/krita-tangentnormal-preview.png
/usr/share/krita/images/krita-tangentnormal.png
/usr/share/krita/images/krita_roundmarkerop.svg
/usr/share/krita/input/kritadefault.profile
/usr/share/krita/input/painttoolsaicompatible.profile
/usr/share/krita/input/photoshopcompatible.profile
/usr/share/krita/metadata/schemas/dc.schema
/usr/share/krita/metadata/schemas/exif.schema
/usr/share/krita/metadata/schemas/exrchannels.schema
/usr/share/krita/metadata/schemas/mkn.schema
/usr/share/krita/metadata/schemas/tiff.schema
/usr/share/krita/metadata/schemas/xmp.schema
/usr/share/krita/metadata/schemas/xmpmm.schema
/usr/share/krita/metadata/schemas/xmprights.schema
/usr/share/krita/paintoppresets/a)_Eraser_Circle.kpp
/usr/share/krita/paintoppresets/b)_Basic-5_Size_default.kpp
/usr/share/krita/palettes/concept-cookie.gpl
/usr/share/krita/palettes/default.gpl
/usr/share/krita/palettes/gradient.gpl
/usr/share/krita/palettes/marker.gpl
/usr/share/krita/palettes/pixelart-16.gpl
/usr/share/krita/palettes/pixelart-32.gpl
/usr/share/krita/palettes/ps.gpl
/usr/share/krita/palettes/swatch-cmyk.gpl
/usr/share/krita/palettes/swatch-colored-grey.gpl
/usr/share/krita/palettes/swatch-rgb.gpl
/usr/share/krita/palettes/swatche.gpl
/usr/share/krita/palettes/web.gpl
/usr/share/krita/patterns/01_canvas.png
/usr/share/krita/patterns/02_rough-canvas.png
/usr/share/krita/patterns/02b_WoofTissue.png
/usr/share/krita/patterns/03_default-paper.png
/usr/share/krita/patterns/04_paper-C-grain.png
/usr/share/krita/patterns/05_paper-torchon.png
/usr/share/krita/patterns/06_hard-grain.png
/usr/share/krita/patterns/08_bump-relief.png
/usr/share/krita/patterns/09_drawed_crosshatched.png
/usr/share/krita/patterns/09b_drawed-CrossedLines.png
/usr/share/krita/patterns/10_drawed_dotted.png
/usr/share/krita/patterns/11_drawed_furry.png
/usr/share/krita/patterns/12_drawed_vertical.png
/usr/share/krita/patterns/13_drawed_swirl.png
/usr/share/krita/patterns/14_texture-rock.png
/usr/share/krita/patterns/15_texture-rockB.png
/usr/share/krita/patterns/16_texture-woody.png
/usr/share/krita/patterns/17_texture-melt.png
/usr/share/krita/patterns/18_texture-bark.png
/usr/share/krita/patterns/18b_WaveFlex.png
/usr/share/krita/patterns/19_texture-crackle.png
/usr/share/krita/patterns/20_texture-vegetal.png
/usr/share/krita/patterns/21_texture-chainmail.png
/usr/share/krita/patterns/22_texture-reptile.png
/usr/share/krita/patterns/23-dynamic-screentone-A.png
/usr/share/krita/patterns/24-dynamic-screentone-B.png
/usr/share/krita/patterns/25-dynamic-screentone-C.png
/usr/share/krita/patterns/26_brush-marks.png
/usr/share/krita/patterns/Abstract_lines.png
/usr/share/krita/patterns/Cross01.pat
/usr/share/krita/patterns/Cross02.pat
/usr/share/krita/patterns/Cross03.pat
/usr/share/krita/patterns/Cross04.pat
/usr/share/krita/patterns/Cross05.pat
/usr/share/krita/patterns/Cross06.pat
/usr/share/krita/patterns/Cross07.pat
/usr/share/krita/patterns/Crumpled_Paper.pat
/usr/share/krita/patterns/Grid01.pat
/usr/share/krita/patterns/Grid02.pat
/usr/share/krita/patterns/Grid03.pat
/usr/share/krita/patterns/Grid04.pat
/usr/share/krita/patterns/Grid05.pat
/usr/share/krita/patterns/HR_PastelPaper_02.pat
/usr/share/krita/patterns/HR_Wall_Paper.pat
/usr/share/krita/patterns/Maze_lines.png
/usr/share/krita/patterns/Pattern01.pat
/usr/share/krita/patterns/Pattern02.pat
/usr/share/krita/patterns/Pattern03.pat
/usr/share/krita/patterns/Pattern04.pat
/usr/share/krita/patterns/Pattern05.pat
/usr/share/krita/patterns/Pattern06.pat
/usr/share/krita/patterns/Rough_Paper.png
/usr/share/krita/patterns/Rough_Wall_With_Impasto.png
/usr/share/krita/patterns/Sand_fine.png
/usr/share/krita/patterns/Squares01.pat
/usr/share/krita/patterns/Squares02.pat
/usr/share/krita/patterns/Squares03.pat
/usr/share/krita/patterns/Squares04.pat
/usr/share/krita/patterns/Squares05.pat
/usr/share/krita/patterns/Squares06.pat
/usr/share/krita/patterns/Squares07.pat
/usr/share/krita/patterns/Squares08.pat
/usr/share/krita/patterns/Squares09.pat
/usr/share/krita/patterns/Squares10.pat
/usr/share/krita/patterns/Stars_Sized.png
/usr/share/krita/patterns/Stripes02.pat
/usr/share/krita/patterns/Stripes03.pat
/usr/share/krita/patterns/Stripes04.pat
/usr/share/krita/patterns/Stripes05.pat
/usr/share/krita/patterns/Stripes06.pat
/usr/share/krita/patterns/Stripes07.pat
/usr/share/krita/patterns/Stripes08.pat
/usr/share/krita/patterns/Stripes09.pat
/usr/share/krita/patterns/Zigzag01.pat
/usr/share/krita/patterns/Zigzag02.pat
/usr/share/krita/patterns/Zigzag03.pat
/usr/share/krita/patterns/Zigzag04.pat
/usr/share/krita/patterns/fractal_pattern.pat
/usr/share/krita/patterns/generic_paper1.pat
/usr/share/krita/patterns/generic_paper2.pat
/usr/share/krita/patterns/hexacolBW__2.pat
/usr/share/krita/pics/dark_arrow_east.png
/usr/share/krita/pics/dark_arrow_north.png
/usr/share/krita/pics/dark_arrow_north_east.png
/usr/share/krita/pics/dark_arrow_north_west.png
/usr/share/krita/pics/dark_arrow_south.png
/usr/share/krita/pics/dark_arrow_south_east.png
/usr/share/krita/pics/dark_arrow_south_west.png
/usr/share/krita/pics/dark_arrow_west.png
/usr/share/krita/pics/dark_krita_tool_assistant.png
/usr/share/krita/pics/dark_template_DIN_A3_landscape.png
/usr/share/krita/pics/dark_template_DIN_A4_portrait.png
/usr/share/krita/pics/dark_template_animation.png
/usr/share/krita/pics/dark_template_comics_empty.png
/usr/share/krita/pics/dark_template_dslr.png
/usr/share/krita/pics/dark_template_ratio_1610.png
/usr/share/krita/pics/dark_template_ratio_2391.png
/usr/share/krita/pics/dark_template_ratio_43.png
/usr/share/krita/pics/dark_template_texture.png
/usr/share/krita/pics/dark_template_web_design.png
/usr/share/krita/pics/extended_color_selector.png
/usr/share/krita/pics/kis_colselng_color_patches.png
/usr/share/krita/pics/kis_colselng_color_triangle.png
/usr/share/krita/pics/kis_colselng_my_paint_shade_selector.png
/usr/share/krita/pics/krita_tool_assistant.png
/usr/share/krita/pics/light_arrow_east.png
/usr/share/krita/pics/light_arrow_north.png
/usr/share/krita/pics/light_arrow_north_east.png
/usr/share/krita/pics/light_arrow_north_west.png
/usr/share/krita/pics/light_arrow_south.png
/usr/share/krita/pics/light_arrow_south_east.png
/usr/share/krita/pics/light_arrow_south_west.png
/usr/share/krita/pics/light_arrow_west.png
/usr/share/krita/pics/light_krita_tool_assistant.png
/usr/share/krita/pics/light_template_DIN_A3_landscape.png
/usr/share/krita/pics/light_template_DIN_A4_portrait.png
/usr/share/krita/pics/light_template_animation.png
/usr/share/krita/pics/light_template_comics_empty.png
/usr/share/krita/pics/light_template_dslr.png
/usr/share/krita/pics/light_template_ratio_1610.png
/usr/share/krita/pics/light_template_ratio_2391.png
/usr/share/krita/pics/light_template_ratio_43.png
/usr/share/krita/pics/light_template_texture.png
/usr/share/krita/pics/light_template_web_design.png
/usr/share/krita/predefined_image_sizes/A3__300_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/A3__600_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/A4__300_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/A4__600_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/A5__300_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/A5__600_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/A6__300_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/A6__600_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/Texture_1024x1024.predefinedimage
/usr/share/krita/predefined_image_sizes/Texture_2048x2048.predefinedimage
/usr/share/krita/predefined_image_sizes/Texture_256x256.predefinedimage
/usr/share/krita/predefined_image_sizes/Texture_4096x4096.predefinedimage
/usr/share/krita/predefined_image_sizes/Texture_512x512.predefinedimage
/usr/share/krita/predefined_image_sizes/US_Legal__300_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/US_Letter__300_ppi_.predefinedimage
/usr/share/krita/predefined_image_sizes/US_Tabloid__300_ppi_.predefinedimage
/usr/share/krita/preset_icons/background.png
/usr/share/krita/preset_icons/emblem_icons/addition.png
/usr/share/krita/preset_icons/emblem_icons/color.png
/usr/share/krita/preset_icons/emblem_icons/comic.png
/usr/share/krita/preset_icons/emblem_icons/edit-pen.png
/usr/share/krita/preset_icons/emblem_icons/emblem_angle_10.png
/usr/share/krita/preset_icons/emblem_icons/emblem_angle_15.png
/usr/share/krita/preset_icons/emblem_icons/emblem_angle_30.png
/usr/share/krita/preset_icons/emblem_icons/emblem_angle_45.png
/usr/share/krita/preset_icons/emblem_icons/emblem_angle_60.png
/usr/share/krita/preset_icons/emblem_icons/emblem_angle_75.png
/usr/share/krita/preset_icons/emblem_icons/emblem_angle_90.png
/usr/share/krita/preset_icons/emblem_icons/emblem_rotation.png
/usr/share/krita/preset_icons/emblem_icons/emblem_tilt.png
/usr/share/krita/preset_icons/emblem_icons/experimental.png
/usr/share/krita/preset_icons/emblem_icons/favorite.png
/usr/share/krita/preset_icons/emblem_icons/love.png
/usr/share/krita/preset_icons/emblem_icons/mechanical.png
/usr/share/krita/preset_icons/emblem_icons/mouse.png
/usr/share/krita/preset_icons/emblem_icons/multidirection.png
/usr/share/krita/preset_icons/emblem_icons/question.png
/usr/share/krita/preset_icons/emblem_icons/sketch.png
/usr/share/krita/preset_icons/emblem_icons/wet.png
/usr/share/krita/preset_icons/emblem_icons/whirlpool.png
/usr/share/krita/preset_icons/tool_icons/acrylic-angled.png
/usr/share/krita/preset_icons/tool_icons/acrylic-fan-used.png
/usr/share/krita/preset_icons/tool_icons/acrylic-flat-old.png
/usr/share/krita/preset_icons/tool_icons/acrylic-flat.png
/usr/share/krita/preset_icons/tool_icons/acrylic-mop.png
/usr/share/krita/preset_icons/tool_icons/acrylic-rounded-used.png
/usr/share/krita/preset_icons/tool_icons/adjustement-contrast.png
/usr/share/krita/preset_icons/tool_icons/adjustement-dark.png
/usr/share/krita/preset_icons/tool_icons/airbrush.png
/usr/share/krita/preset_icons/tool_icons/blending-stump.png
/usr/share/krita/preset_icons/tool_icons/blur_soft.png
/usr/share/krita/preset_icons/tool_icons/chalk-square.png
/usr/share/krita/preset_icons/tool_icons/charcoal-block.png
/usr/share/krita/preset_icons/tool_icons/charcoal-pencil-large.png
/usr/share/krita/preset_icons/tool_icons/charcoal-pencil-medium.png
/usr/share/krita/preset_icons/tool_icons/charcoal-pencil-thin.png
/usr/share/krita/preset_icons/tool_icons/clone.png
/usr/share/krita/preset_icons/tool_icons/color-effect.png
/usr/share/krita/preset_icons/tool_icons/colored-pencil.png
/usr/share/krita/preset_icons/tool_icons/deform.png
/usr/share/krita/preset_icons/tool_icons/eraser-hard.png
/usr/share/krita/preset_icons/tool_icons/eraser-kneaded.png
/usr/share/krita/preset_icons/tool_icons/eraser-large.png
/usr/share/krita/preset_icons/tool_icons/eraser-mechanical.png
/usr/share/krita/preset_icons/tool_icons/experimental.png
/usr/share/krita/preset_icons/tool_icons/filter.png
/usr/share/krita/preset_icons/tool_icons/gel-pen.png
/usr/share/krita/preset_icons/tool_icons/graphite.png
/usr/share/krita/preset_icons/tool_icons/grid.png
/usr/share/krita/preset_icons/tool_icons/ink-G-pen.png
/usr/share/krita/preset_icons/tool_icons/ink-brush.png
/usr/share/krita/preset_icons/tool_icons/ink-pen-atom.png
/usr/share/krita/preset_icons/tool_icons/ink-pen-glass.png
/usr/share/krita/preset_icons/tool_icons/inking_brush.png
/usr/share/krita/preset_icons/tool_icons/inking_brush_blurry.png
/usr/share/krita/preset_icons/tool_icons/inking_dynamic_pen.png
/usr/share/krita/preset_icons/tool_icons/inking_dynamic_pen_though.png
/usr/share/krita/preset_icons/tool_icons/inking_fine-line_medium.png
/usr/share/krita/preset_icons/tool_icons/inking_fine-line_tiny.png
/usr/share/krita/preset_icons/tool_icons/inking_pen_bumpy.png
/usr/share/krita/preset_icons/tool_icons/inking_pen_bumpy_though.png
/usr/share/krita/preset_icons/tool_icons/inking_pen_calligraphic.png
/usr/share/krita/preset_icons/tool_icons/knife-rake.png
/usr/share/krita/preset_icons/tool_icons/knife.png
/usr/share/krita/preset_icons/tool_icons/large-rounded-cut.png
/usr/share/krita/preset_icons/tool_icons/marker-large.png
/usr/share/krita/preset_icons/tool_icons/marker-old.png
/usr/share/krita/preset_icons/tool_icons/marker.png
/usr/share/krita/preset_icons/tool_icons/mechanical-pencil.png
/usr/share/krita/preset_icons/tool_icons/oil-filbert.png
/usr/share/krita/preset_icons/tool_icons/oil-flat-large.png
/usr/share/krita/preset_icons/tool_icons/oil-round-hard.png
/usr/share/krita/preset_icons/tool_icons/paint-roller.png
/usr/share/krita/preset_icons/tool_icons/pastel.png
/usr/share/krita/preset_icons/tool_icons/pencil-black-stone.png
/usr/share/krita/preset_icons/tool_icons/pencil-double-ring.png
/usr/share/krita/preset_icons/tool_icons/rigger-brush.png
/usr/share/krita/preset_icons/tool_icons/round_marker_detail.png
/usr/share/krita/preset_icons/tool_icons/screentone-indicator.png
/usr/share/krita/preset_icons/tool_icons/shape.png
/usr/share/krita/preset_icons/tool_icons/sketching_wide_47.png
/usr/share/krita/preset_icons/tool_icons/sketching_wide_bristles.png
/usr/share/krita/preset_icons/tool_icons/special-effect-used-brush.png
/usr/share/krita/preset_icons/tool_icons/stamp.png
/usr/share/krita/preset_icons/tool_icons/stylus-colored-ring.png
/usr/share/krita/preset_icons/tool_icons/stylus-colored.png
/usr/share/krita/preset_icons/tool_icons/stylus-experimental.png
/usr/share/krita/preset_icons/tool_icons/stylus-white.png
/usr/share/krita/preset_icons/tool_icons/stylus.png
/usr/share/krita/preset_icons/tool_icons/sumi-e.png
/usr/share/krita/preset_icons/tool_icons/synthetic-filbert.png
/usr/share/krita/preset_icons/tool_icons/synthetic-large-bright-used.png
/usr/share/krita/preset_icons/tool_icons/synthetic-large-bright.png
/usr/share/krita/preset_icons/tool_icons/synthetic-medium.png
/usr/share/krita/preset_icons/tool_icons/synthetic-thin.png
/usr/share/krita/preset_icons/tool_icons/synthetic-very-old.png
/usr/share/krita/preset_icons/tool_icons/technical-pen.png
/usr/share/krita/preset_icons/tool_icons/texture-indicator.png
/usr/share/krita/preset_icons/tool_icons/thin-stylus-tablet.png
/usr/share/krita/preset_icons/tool_icons/wand.png
/usr/share/krita/preset_icons/tool_icons/watercolor-brush-medium.png
/usr/share/krita/preset_icons/tool_icons/watercolor-flat.png
/usr/share/krita/preset_icons/tool_icons/wide_brush_big.png
/usr/share/krita/preset_icons/tool_icons/wide_brush_blurry.png
/usr/share/krita/preset_icons/tool_icons/wide_dull_round.png
/usr/share/krita/qmlthemes/default/colors.js
/usr/share/krita/qmlthemes/default/fonts.js
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-Black.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-BlackIt.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-Bold.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-BoldIt.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-ExtraLight.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-ExtraLightIt.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-It.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-Light.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-LightIt.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-Regular.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-Semibold.otf
/usr/share/krita/qmlthemes/default/fonts/SourceSansPro-SemiboldIt.otf
/usr/share/krita/qmlthemes/default/icons/A4landscape-black.svg
/usr/share/krita/qmlthemes/default/icons/A4portrait-black.svg
/usr/share/krita/qmlthemes/default/icons/add-black.svg
/usr/share/krita/qmlthemes/default/icons/add.svg
/usr/share/krita/qmlthemes/default/icons/apply-black.svg
/usr/share/krita/qmlthemes/default/icons/apply.svg
/usr/share/krita/qmlthemes/default/icons/back.svg
/usr/share/krita/qmlthemes/default/icons/camera-black.svg
/usr/share/krita/qmlthemes/default/icons/cancel-black.svg
/usr/share/krita/qmlthemes/default/icons/checkbox-checked.svg
/usr/share/krita/qmlthemes/default/icons/checkbox-unchecked.svg
/usr/share/krita/qmlthemes/default/icons/checker-small.svg
/usr/share/krita/qmlthemes/default/icons/close.svg
/usr/share/krita/qmlthemes/default/icons/color_wheel.svg
/usr/share/krita/qmlthemes/default/icons/colorpicker.svg
/usr/share/krita/qmlthemes/default/icons/combo-arrows-white.svg
/usr/share/krita/qmlthemes/default/icons/crop-black.svg
/usr/share/krita/qmlthemes/default/icons/crop.svg
/usr/share/krita/qmlthemes/default/icons/delete-black.svg
/usr/share/krita/qmlthemes/default/icons/delete.svg
/usr/share/krita/qmlthemes/default/icons/down.svg
/usr/share/krita/qmlthemes/default/icons/edit.svg
/usr/share/krita/qmlthemes/default/icons/erase.svg
/usr/share/krita/qmlthemes/default/icons/expansionmarker.svg
/usr/share/krita/qmlthemes/default/icons/fileclip-black.svg
/usr/share/krita/qmlthemes/default/icons/fileclip.svg
/usr/share/krita/qmlthemes/default/icons/filenew-black.svg
/usr/share/krita/qmlthemes/default/icons/filenew.svg
/usr/share/krita/qmlthemes/default/icons/fileopen-black.svg
/usr/share/krita/qmlthemes/default/icons/fileopen.svg
/usr/share/krita/qmlthemes/default/icons/filesave.svg
/usr/share/krita/qmlthemes/default/icons/filesaveas.svg
/usr/share/krita/qmlthemes/default/icons/fileshare.svg
/usr/share/krita/qmlthemes/default/icons/fill-black.svg
/usr/share/krita/qmlthemes/default/icons/fill.svg
/usr/share/krita/qmlthemes/default/icons/filter_delete-black.svg
/usr/share/krita/qmlthemes/default/icons/filter_load-black.svg
/usr/share/krita/qmlthemes/default/icons/filter_save-black.svg
/usr/share/krita/qmlthemes/default/icons/forward.svg
/usr/share/krita/qmlthemes/default/icons/gradient-black.svg
/usr/share/krita/qmlthemes/default/icons/gradient.svg
/usr/share/krita/qmlthemes/default/icons/help.svg
/usr/share/krita/qmlthemes/default/icons/krita_sketch.svg
/usr/share/krita/qmlthemes/default/icons/layer_clear.svg
/usr/share/krita/qmlthemes/default/icons/layer_duplicate.svg
/usr/share/krita/qmlthemes/default/icons/layer_filter-black.svg
/usr/share/krita/qmlthemes/default/icons/layer_group-black.svg
/usr/share/krita/qmlthemes/default/icons/layer_move_down.svg
/usr/share/krita/qmlthemes/default/icons/layer_move_left.svg
/usr/share/krita/qmlthemes/default/icons/layer_move_right.svg
/usr/share/krita/qmlthemes/default/icons/layer_move_up.svg
/usr/share/krita/qmlthemes/default/icons/layer_paint-black.svg
/usr/share/krita/qmlthemes/default/icons/locked_off-black.svg
/usr/share/krita/qmlthemes/default/icons/locked_off-small.svg
/usr/share/krita/qmlthemes/default/icons/locked_on-black.svg
/usr/share/krita/qmlthemes/default/icons/locked_on-small.svg
/usr/share/krita/qmlthemes/default/icons/minimize.svg
/usr/share/krita/qmlthemes/default/icons/mirror_c-black.svg
/usr/share/krita/qmlthemes/default/icons/mirror_h-black.svg
/usr/share/krita/qmlthemes/default/icons/mirror_v-black.svg
/usr/share/krita/qmlthemes/default/icons/move-black.svg
/usr/share/krita/qmlthemes/default/icons/move.svg
/usr/share/krita/qmlthemes/default/icons/paint-black.svg
/usr/share/krita/qmlthemes/default/icons/paint.svg
/usr/share/krita/qmlthemes/default/icons/palette-add-black.svg
/usr/share/krita/qmlthemes/default/icons/palette-black.svg
/usr/share/krita/qmlthemes/default/icons/palette-delete-black.svg
/usr/share/krita/qmlthemes/default/icons/palette.svg
/usr/share/krita/qmlthemes/default/icons/redo.svg
/usr/share/krita/qmlthemes/default/icons/select-add.svg
/usr/share/krita/qmlthemes/default/icons/select-apply.svg
/usr/share/krita/qmlthemes/default/icons/select-area.svg
/usr/share/krita/qmlthemes/default/icons/select-color.svg
/usr/share/krita/qmlthemes/default/icons/select-deselect.svg
/usr/share/krita/qmlthemes/default/icons/select-hide.svg
/usr/share/krita/qmlthemes/default/icons/select-intersect.svg
/usr/share/krita/qmlthemes/default/icons/select-polygon.svg
/usr/share/krita/qmlthemes/default/icons/select-rectangle.svg
/usr/share/krita/qmlthemes/default/icons/select-replace.svg
/usr/share/krita/qmlthemes/default/icons/select-reselect.svg
/usr/share/krita/qmlthemes/default/icons/select-show.svg
/usr/share/krita/qmlthemes/default/icons/select-sub.svg
/usr/share/krita/qmlthemes/default/icons/settings.svg
/usr/share/krita/qmlthemes/default/icons/switch.svg
/usr/share/krita/qmlthemes/default/icons/transform-black.svg
/usr/share/krita/qmlthemes/default/icons/transform.svg
/usr/share/krita/qmlthemes/default/icons/undo.svg
/usr/share/krita/qmlthemes/default/icons/up.svg
/usr/share/krita/qmlthemes/default/icons/visible_off-black.svg
/usr/share/krita/qmlthemes/default/icons/visible_off-small.svg
/usr/share/krita/qmlthemes/default/icons/visible_off.svg
/usr/share/krita/qmlthemes/default/icons/visible_on-black.svg
/usr/share/krita/qmlthemes/default/icons/visible_on-small.svg
/usr/share/krita/qmlthemes/default/icons/visible_on.svg
/usr/share/krita/qmlthemes/default/icons/web.svg
/usr/share/krita/qmlthemes/default/images/busyindicator.png
/usr/share/krita/qmlthemes/default/images/divider.png
/usr/share/krita/qmlthemes/default/images/header_krita_sketch.png
/usr/share/krita/qmlthemes/default/images/header_krita_sketch_light.png
/usr/share/krita/qmlthemes/default/images/kritasketch.png
/usr/share/krita/qmlthemes/default/images/shadow.png
/usr/share/krita/qmlthemes/default/sizes.js
/usr/share/krita/qmlthemes/default/theme.qml
/usr/share/krita/shortcuts/krita_default.shortcuts
/usr/share/krita/shortcuts/paint_tool_sai_compatible.shortcuts
/usr/share/krita/shortcuts/photoshop_compatible.shortcuts
/usr/share/krita/shortcuts/tablet_pro.shortcuts
/usr/share/krita/styles/markers.svg
/usr/share/krita/symbols/BalloonSymbols.svg
/usr/share/krita/symbols/pepper_carrot_speech_bubbles.svg
/usr/share/krita/symbols/preset_icons.svg
/usr/share/krita/templates/animation/.directory
/usr/share/krita/templates/animation/.source/Anim-Jp-EN.kra
/usr/share/krita/templates/animation/.source/Anim-Jp-JP.kra
/usr/share/krita/templates/animation/Anim-Jp-EN.desktop
/usr/share/krita/templates/animation/Anim-Jp-JP.desktop
/usr/share/krita/templates/comics/.directory
/usr/share/krita/templates/comics/.source/BD-EuroTemplate.kra
/usr/share/krita/templates/comics/.source/Comics-USTemplate.kra
/usr/share/krita/templates/comics/.source/Manga-JpTemplate.kra
/usr/share/krita/templates/comics/.source/a4_waffle_grid.kra
/usr/share/krita/templates/comics/BD-EuroTemplate.desktop
/usr/share/krita/templates/comics/Comics-USTemplate.desktop
/usr/share/krita/templates/comics/Manga-JpTemplate.desktop
/usr/share/krita/templates/comics/a4_waffle_grid.desktop
/usr/share/krita/templates/design/.directory
/usr/share/krita/templates/design/.source/Designcinema16_10_2484x1200_96dpiRGB_8bit_.kra
/usr/share/krita/templates/design/.source/Designcinema2.39_1_2484x1040_96dpiRGB_8bit_.kra
/usr/share/krita/templates/design/.source/DesignpresentationA3Landscape_4960x3508_300dpiRGB_8bit_.kra
/usr/share/krita/templates/design/.source/DesignpresentationA4portrait_2480x3508_300dpiRGB_8bit_.kra
/usr/share/krita/templates/design/.source/Designscreen4_3_2250x1680_96dpiRGB_8bit_.kra
/usr/share/krita/templates/design/.source/web_design.kra
/usr/share/krita/templates/design/Designcinema16_10_2484x1200_96dpiRGB_8bit_.desktop
/usr/share/krita/templates/design/Designcinema2.39_1_2484x1040_96dpiRGB_8bit_.desktop
/usr/share/krita/templates/design/DesignpresentationA3Landscape_4960x3508_300dpiRGB_8bit_.desktop
/usr/share/krita/templates/design/DesignpresentationA4portrait_2480x3508_300dpiRGB_8bit_.desktop
/usr/share/krita/templates/design/Designscreen4_3_2250x1680_96dpiRGB_8bit_.desktop
/usr/share/krita/templates/design/web_design.desktop
/usr/share/krita/templates/dslr/.directory
/usr/share/krita/templates/dslr/.source/Canon_550D_5184x3456.kra
/usr/share/krita/templates/dslr/.source/Canon_5Dmk3_5760x3840.kra
/usr/share/krita/templates/dslr/.source/Nikon_D3000_3872x2592.kra
/usr/share/krita/templates/dslr/.source/Nikon_D5000_4288x2848.kra
/usr/share/krita/templates/dslr/.source/Nikon_D7000_4928x3264.kra
/usr/share/krita/templates/dslr/Canon_550D_5184x3456.desktop
/usr/share/krita/templates/dslr/Canon_5Dmk3_5760x3840.desktop
/usr/share/krita/templates/dslr/Nikon_D3000_3872x2592.desktop
/usr/share/krita/templates/dslr/Nikon_D5000_4288x2848.desktop
/usr/share/krita/templates/dslr/Nikon_D7000_4928x3264.desktop
/usr/share/krita/templates/texture/.directory
/usr/share/krita/templates/texture/.source/Texture1024x10248bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture1k32bitscalar.kra
/usr/share/krita/templates/texture/.source/Texture1k8bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture2048x20488bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture256x2568bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture2k32bitscalar.kra
/usr/share/krita/templates/texture/.source/Texture2k8bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture4096x40968bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture4k32bitscalar.kra
/usr/share/krita/templates/texture/.source/Texture4k8bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture512x5128bitsrgb.kra
/usr/share/krita/templates/texture/.source/Texture8k32bitscalar.kra
/usr/share/krita/templates/texture/.source/Texture8k8bitsrgb.kra
/usr/share/krita/templates/texture/Texture1024x10248bitsrgb.desktop
/usr/share/krita/templates/texture/Texture1k32bitscalar.desktop
/usr/share/krita/templates/texture/Texture1k8bitsrgb.desktop
/usr/share/krita/templates/texture/Texture2048x20488bitsrgb.desktop
/usr/share/krita/templates/texture/Texture256x2568bitsrgb.desktop
/usr/share/krita/templates/texture/Texture2k32bitscalar.desktop
/usr/share/krita/templates/texture/Texture2k8bitsrgb.desktop
/usr/share/krita/templates/texture/Texture4096x40968bitsrgb.desktop
/usr/share/krita/templates/texture/Texture4k32bitscalar.desktop
/usr/share/krita/templates/texture/Texture4k8bitsrgb.desktop
/usr/share/krita/templates/texture/Texture512x5128bitsrgb.desktop
/usr/share/krita/templates/texture/Texture8k32bitscalar.desktop
/usr/share/krita/templates/texture/Texture8k8bitsrgb.desktop
/usr/share/krita/workspaces/Animation.kws
/usr/share/krita/workspaces/Big_Paint.kws
/usr/share/krita/workspaces/Big_Paint_2.kws
/usr/share/krita/workspaces/Big_Vector.kws
/usr/share/krita/workspaces/Default.kws
/usr/share/krita/workspaces/Minimal.kws
/usr/share/krita/workspaces/Small_Vector.kws
/usr/share/krita/workspaces/VFX_Paint.kws
/usr/share/kritaplugins/buginfo.xmlgui
/usr/share/kritaplugins/clonesarray.xmlgui
/usr/share/kritaplugins/colorrange.xmlgui
/usr/share/kritaplugins/colorspaceconversion.xmlgui
/usr/share/kritaplugins/histogram.xmlgui
/usr/share/kritaplugins/imageseparate.xmlgui
/usr/share/kritaplugins/imagesize.xmlgui
/usr/share/kritaplugins/imagesplit.xmlgui
/usr/share/kritaplugins/layersplit.xmlgui
/usr/share/kritaplugins/metadataeditor.xmlgui
/usr/share/kritaplugins/metadataeditor/dublincore.xmlgui
/usr/share/kritaplugins/metadataeditor/exif.xmlgui
/usr/share/kritaplugins/modify_selection.xmlgui
/usr/share/kritaplugins/offsetimage.xmlgui
/usr/share/kritaplugins/resourcemanager.xmlgui
/usr/share/kritaplugins/rotateimage.xmlgui
/usr/share/kritaplugins/shearimage.xmlgui
/usr/share/kritaplugins/waveletdecompose.xmlgui
/usr/share/metainfo/org.kde.krita.appdata.xml
/usr/share/xdg/kritarc

%files dev
%defattr(-,root,root,-)
/usr/lib64/libkritabasicflakes.so
/usr/lib64/libkritacolor.so
/usr/lib64/libkritacolord.so
/usr/lib64/libkritacommand.so
/usr/lib64/libkritaflake.so
/usr/lib64/libkritaglobal.so
/usr/lib64/libkritaimage.so
/usr/lib64/libkritaimpex.so
/usr/lib64/libkritalibbrush.so
/usr/lib64/libkritalibkis.so
/usr/lib64/libkritalibkra.so
/usr/lib64/libkritalibpaintop.so
/usr/lib64/libkritametadata.so
/usr/lib64/libkritaodf.so
/usr/lib64/libkritapigment.so
/usr/lib64/libkritaplugin.so
/usr/lib64/libkritapsd.so
/usr/lib64/libkritaqml.so
/usr/lib64/libkritastore.so
/usr/lib64/libkritatext.so
/usr/lib64/libkritatextlayout.so
/usr/lib64/libkritaui.so
/usr/lib64/libkritavectorimage.so
/usr/lib64/libkritaversion.so
/usr/lib64/libkritawidgets.so
/usr/lib64/libkritawidgetutils.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/kritaplugins/krita_colorspaces_extensions.so
/usr/lib64/kritaplugins/krita_filtereffects.so
/usr/lib64/kritaplugins/krita_flaketools.so
/usr/lib64/kritaplugins/krita_karbontools.so
/usr/lib64/kritaplugins/krita_raw_import.so
/usr/lib64/kritaplugins/krita_shape_artistictext.so
/usr/lib64/kritaplugins/krita_shape_image.so
/usr/lib64/kritaplugins/krita_shape_paths.so
/usr/lib64/kritaplugins/krita_shape_text.so
/usr/lib64/kritaplugins/krita_tool_basicflakes.so
/usr/lib64/kritaplugins/krita_tool_svgtext.so
/usr/lib64/kritaplugins/kritaanimationdocker.so
/usr/lib64/kritaplugins/kritaanimationrenderer.so
/usr/lib64/kritaplugins/kritaarrangedocker.so
/usr/lib64/kritaplugins/kritaartisticcolorselector.so
/usr/lib64/kritaplugins/kritaasccdl.so
/usr/lib64/kritaplugins/kritaassistanttool.so
/usr/lib64/kritaplugins/kritablurfilter.so
/usr/lib64/kritaplugins/kritabrushexport.so
/usr/lib64/kritaplugins/kritabrushimport.so
/usr/lib64/kritaplugins/kritabuginfo.so
/usr/lib64/kritaplugins/kritachanneldocker.so
/usr/lib64/kritaplugins/kritaclonesarray.so
/usr/lib64/kritaplugins/kritacolorgenerator.so
/usr/lib64/kritaplugins/kritacolorrange.so
/usr/lib64/kritaplugins/kritacolorselectorng.so
/usr/lib64/kritaplugins/kritacolorsfilters.so
/usr/lib64/kritaplugins/kritacolorsmudgepaintop.so
/usr/lib64/kritaplugins/kritacolorspaceconversion.so
/usr/lib64/kritaplugins/kritacompositiondocker.so
/usr/lib64/kritaplugins/kritaconvertheighttonormalmap.so
/usr/lib64/kritaplugins/kritaconvolutionfilters.so
/usr/lib64/kritaplugins/kritacsvexport.so
/usr/lib64/kritaplugins/kritacsvimport.so
/usr/lib64/kritaplugins/kritacurvepaintop.so
/usr/lib64/kritaplugins/kritadefaultdockers.so
/usr/lib64/kritaplugins/kritadefaultpaintops.so
/usr/lib64/kritaplugins/kritadefaulttools.so
/usr/lib64/kritaplugins/kritadeformpaintop.so
/usr/lib64/kritaplugins/kritadigitalmixer.so
/usr/lib64/kritaplugins/kritadodgeburn.so
/usr/lib64/kritaplugins/kritaedgedetection.so
/usr/lib64/kritaplugins/kritaembossfilter.so
/usr/lib64/kritaplugins/kritaexample.so
/usr/lib64/kritaplugins/kritaexperimentpaintop.so
/usr/lib64/kritaplugins/kritaexrexport.so
/usr/lib64/kritaplugins/kritaexrimport.so
/usr/lib64/kritaplugins/kritaextensioncolorsfilters.so
/usr/lib64/kritaplugins/kritafastcolortransferfilter.so
/usr/lib64/kritaplugins/kritafilterop.so
/usr/lib64/kritaplugins/kritagamutmask.so
/usr/lib64/kritaplugins/kritagradientmap.so
/usr/lib64/kritaplugins/kritagriddocker.so
/usr/lib64/kritaplugins/kritagridpaintop.so
/usr/lib64/kritaplugins/kritahairypaintop.so
/usr/lib64/kritaplugins/kritahalftone.so
/usr/lib64/kritaplugins/kritahatchingpaintop.so
/usr/lib64/kritaplugins/kritaheightmapexport.so
/usr/lib64/kritaplugins/kritaheightmapimport.so
/usr/lib64/kritaplugins/kritahistogram.so
/usr/lib64/kritaplugins/kritahistogramdocker.so
/usr/lib64/kritaplugins/kritahistorydocker.so
/usr/lib64/kritaplugins/kritaimageenhancement.so
/usr/lib64/kritaplugins/kritaimagesize.so
/usr/lib64/kritaplugins/kritaimagesplit.so
/usr/lib64/kritaplugins/kritaindexcolors.so
/usr/lib64/kritaplugins/kritajpegexport.so
/usr/lib64/kritaplugins/kritajpegimport.so
/usr/lib64/kritaplugins/kritakraexport.so
/usr/lib64/kritaplugins/kritakraimport.so
/usr/lib64/kritaplugins/kritalayergroupswitcher.so
/usr/lib64/kritaplugins/kritalayersplit.so
/usr/lib64/kritaplugins/kritalcmsengine.so
/usr/lib64/kritaplugins/kritalevelfilter.so
/usr/lib64/kritaplugins/kritalogdocker.so
/usr/lib64/kritaplugins/kritametadataeditor.so
/usr/lib64/kritaplugins/kritamodifyselection.so
/usr/lib64/kritaplugins/kritanoisefilter.so
/usr/lib64/kritaplugins/kritanormalize.so
/usr/lib64/kritaplugins/kritaoffsetimage.so
/usr/lib64/kritaplugins/kritaoilpaintfilter.so
/usr/lib64/kritaplugins/kritaoraexport.so
/usr/lib64/kritaplugins/kritaoraimport.so
/usr/lib64/kritaplugins/kritaoverviewdocker.so
/usr/lib64/kritaplugins/kritapalettedocker.so
/usr/lib64/kritaplugins/kritaparticlepaintop.so
/usr/lib64/kritaplugins/kritapatterndocker.so
/usr/lib64/kritaplugins/kritapatterngenerator.so
/usr/lib64/kritaplugins/kritaphongbumpmap.so
/usr/lib64/kritaplugins/kritapixelizefilter.so
/usr/lib64/kritaplugins/kritapngexport.so
/usr/lib64/kritaplugins/kritapngimport.so
/usr/lib64/kritaplugins/kritaposterize.so
/usr/lib64/kritaplugins/kritappmexport.so
/usr/lib64/kritaplugins/kritappmimport.so
/usr/lib64/kritaplugins/kritapresetdocker.so
/usr/lib64/kritaplugins/kritapresethistory.so
/usr/lib64/kritaplugins/kritapsdexport.so
/usr/lib64/kritaplugins/kritapsdimport.so
/usr/lib64/kritaplugins/kritaqimageioexport.so
/usr/lib64/kritaplugins/kritaqimageioimport.so
/usr/lib64/kritaplugins/kritaqmic.so
/usr/lib64/kritaplugins/kritaqmlexport.so
/usr/lib64/kritaplugins/kritaraindropsfilter.so
/usr/lib64/kritaplugins/kritarandompickfilter.so
/usr/lib64/kritaplugins/kritaresourcemanager.so
/usr/lib64/kritaplugins/kritarotateimage.so
/usr/lib64/kritaplugins/kritaroundcornersfilter.so
/usr/lib64/kritaplugins/kritaroundmarkerpaintop.so
/usr/lib64/kritaplugins/kritaselectiontools.so
/usr/lib64/kritaplugins/kritaseparatechannels.so
/usr/lib64/kritaplugins/kritashearimage.so
/usr/lib64/kritaplugins/kritasketchpaintop.so
/usr/lib64/kritaplugins/kritasmallcolorselector.so
/usr/lib64/kritaplugins/kritasmalltilesfilter.so
/usr/lib64/kritaplugins/kritaspecificcolorselector.so
/usr/lib64/kritaplugins/kritaspraypaintop.so
/usr/lib64/kritaplugins/kritaspriterexport.so
/usr/lib64/kritaplugins/kritasvgcollectiondocker.so
/usr/lib64/kritaplugins/kritasvgimport.so
/usr/lib64/kritaplugins/kritatangentnormalpaintop.so
/usr/lib64/kritaplugins/kritatasksetdocker.so
/usr/lib64/kritaplugins/kritatgaexport.so
/usr/lib64/kritaplugins/kritatgaimport.so
/usr/lib64/kritaplugins/kritathreshold.so
/usr/lib64/kritaplugins/kritatiffexport.so
/usr/lib64/kritaplugins/kritatiffimport.so
/usr/lib64/kritaplugins/kritatoolSmartPatch.so
/usr/lib64/kritaplugins/kritatoolcrop.so
/usr/lib64/kritaplugins/kritatooldyna.so
/usr/lib64/kritaplugins/kritatoollazybrush.so
/usr/lib64/kritaplugins/kritatoolpolygon.so
/usr/lib64/kritaplugins/kritatoolpolyline.so
/usr/lib64/kritaplugins/kritatooltransform.so
/usr/lib64/kritaplugins/kritatouchdocker.so
/usr/lib64/kritaplugins/kritaunsharpfilter.so
/usr/lib64/kritaplugins/kritavideoexport.so
/usr/lib64/kritaplugins/kritawavefilter.so
/usr/lib64/kritaplugins/kritawaveletdecompose.so
/usr/lib64/kritaplugins/kritaxcfimport.so
/usr/lib64/libkritabasicflakes.so.18
/usr/lib64/libkritabasicflakes.so.18.0.0
/usr/lib64/libkritacolor.so.18
/usr/lib64/libkritacolor.so.18.0.0
/usr/lib64/libkritacolord.so.18
/usr/lib64/libkritacolord.so.18.0.0
/usr/lib64/libkritacommand.so.18
/usr/lib64/libkritacommand.so.18.0.0
/usr/lib64/libkritaflake.so.18
/usr/lib64/libkritaflake.so.18.0.0
/usr/lib64/libkritaglobal.so.18
/usr/lib64/libkritaglobal.so.18.0.0
/usr/lib64/libkritaimage.so.18
/usr/lib64/libkritaimage.so.18.0.0
/usr/lib64/libkritaimpex.so.18
/usr/lib64/libkritaimpex.so.18.0.0
/usr/lib64/libkritalibbrush.so.18
/usr/lib64/libkritalibbrush.so.18.0.0
/usr/lib64/libkritalibkis.so.18
/usr/lib64/libkritalibkis.so.18.0.0
/usr/lib64/libkritalibkra.so.18
/usr/lib64/libkritalibkra.so.18.0.0
/usr/lib64/libkritalibpaintop.so.18
/usr/lib64/libkritalibpaintop.so.18.0.0
/usr/lib64/libkritametadata.so.18
/usr/lib64/libkritametadata.so.18.0.0
/usr/lib64/libkritaodf.so.18
/usr/lib64/libkritaodf.so.18.0.0
/usr/lib64/libkritapigment.so.18
/usr/lib64/libkritapigment.so.18.0.0
/usr/lib64/libkritaplugin.so.18
/usr/lib64/libkritaplugin.so.18.0.0
/usr/lib64/libkritapsd.so.18
/usr/lib64/libkritapsd.so.18.0.0
/usr/lib64/libkritaqml.so.18
/usr/lib64/libkritaqml.so.18.0.0
/usr/lib64/libkritastore.so.18
/usr/lib64/libkritastore.so.18.0.0
/usr/lib64/libkritatext.so.18
/usr/lib64/libkritatext.so.18.0.0
/usr/lib64/libkritatextlayout.so.18
/usr/lib64/libkritatextlayout.so.18.0.0
/usr/lib64/libkritaui.so.18
/usr/lib64/libkritaui.so.18.0.0
/usr/lib64/libkritavectorimage.so.18
/usr/lib64/libkritavectorimage.so.18.0.0
/usr/lib64/libkritaversion.so.18
/usr/lib64/libkritaversion.so.18.0.0
/usr/lib64/libkritawidgets.so.18
/usr/lib64/libkritawidgets.so.18.0.0
/usr/lib64/libkritawidgetutils.so.18
/usr/lib64/libkritawidgetutils.so.18.0.0
/usr/lib64/qt5/qml/org/krita/draganddrop/libdraganddropplugin.so
/usr/lib64/qt5/qml/org/krita/draganddrop/qmldir
/usr/lib64/qt5/qml/org/krita/sketch/components/BusyIndicator.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Button.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/CategorySwitcher.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/CheckBox.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/ColorSwatch.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Dialog.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Divider.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/DropShadow.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/ExpandingListView.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Header.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Label.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/ListItem.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/MessageStack.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/NewImageList.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/NewsList.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Page.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/PageStack.js
/usr/lib64/qt5/qml/org/krita/sketch/components/PageStack.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/PanelTextField.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/RangeCombo.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/RangeInput.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/RecentFilesList.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/ScrollDecorator.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Shadow.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Slider.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/TextField.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/TextFieldMultiline.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/Tooltip.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/VirtualKeyboard.qml
/usr/lib64/qt5/qml/org/krita/sketch/components/qmldir
/usr/lib64/qt5/qml/org/krita/sketch/libkritasketchplugin.so
/usr/lib64/qt5/qml/org/krita/sketch/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/krita/COPYING
/usr/share/doc/krita/COPYING-CMAKE-SCRIPTS
/usr/share/doc/krita/cmake_modules_COPYING-CMAKE-SCRIPTS
/usr/share/doc/krita/krita_data_aboutdata_LICENSE
/usr/share/doc/krita/krita_integration_LICENSE
/usr/share/doc/krita/krita_integration_kritaquicklook_LICENSE
/usr/share/doc/krita/packaging_windows_installer_license_gpl-3.0.rtf
/usr/share/doc/krita/plugins_impex_raw_3rdparty_libkdcraw_COPYING
/usr/share/doc/krita/plugins_impex_raw_3rdparty_libkdcraw_COPYING-CMAKE-SCRIPTS
/usr/share/doc/krita/plugins_impex_raw_3rdparty_libkdcraw_COPYING.LIB
